### ISSUE TITLE
Quick Access UI unresponsive (MacOS Iris Intel / Chrome / Multi-screen graphic card bug)

### ISSUE THREAD

**Issue by KevinGimbel** [passbolt/passbolt_browser_extension#100]
## Extension UI unresponsive
* Passbolt Version: 2.12.1
* Platform and Target:
-- Browser: Chrome 83.0.4103.106 (Official Build) (64-bit)
-- Web server: nginx/1.14.0
-- User OS: MacOS 10.15.5

### What you did
Used the browser extension to copy a password

### What happened
When clicking the "clipboard" to copy the password, the spinner shows up but gets "stuck" and the extension UI does nothing.

The password is still copied!

### What you expected to happen

The UI should not get "stuck" or "freeze".

**Comment by cedricalfonsi** [comment]
Hello @kevingimbel,

Could you precise us where do you encounter this issue? In the Quickaccess or in the main UI of the application? The quickaccess is the small application that appears after clicking on the passbolt toolbar icon.

Additionally could you copy/paste here the browser console output, it might help to debug you.
How to see browser console (that is different from regular console):

- Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
- Chrome: https://stackoverflow.com/a/10258029/4063145

**Comment by kevingimbel** [comment]
> Could you precise us where do you encounter this issue?

The issue is encountered every time I click the Extension (Quickaccess) to copy a password. The extension freezes as soon as I 
a) Copy a password by clicking on the dots 
b) Try and create a new password
c) Try and enter my password to login to passbolt itself

I checked the console output but it doesn't show anything. 


Here's a screen recording showing the issue https://youtu.be/HqBvIfYXh1w

**Comment by cedricalfonsi** [comment]
We have already seen this bug on a very specific setup: Chrome + Macbook pro + additional screen. Do you have a similar setup?

**Comment by kevingimbel** [comment]
This is exactly my setup. 😂 

I'm using:

- MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
- Processor: 2,3 GHz Quad-Core Intel Core i5
- RAM: 16GB
- Graphics: Intel Iris Plus Graphics 655 1536 MB

My external monitor is a 27-inch (1920 x 1080) Acer monitor.

If you need any additional info please let me know!

**Comment by kevingimbel** [comment]
I am no longer seeing this issue with Chrome version `85.0.4183.102 (64-bit)` on MacOS 10.15
