### ISSUE TITLE
Uncaught SyntaxError: Identifier 'eventMap' has already been declared

### ISSUE THREAD

**Issue by felvct** [passbolt/passbolt_browser_extension#101]
## ISSUE NAME
* Passbolt Version:2.13.4
* Platform and Target:
-- Browser: GOOGLE CHROME Version 83.0.4103.97
-- etc.: Issue within Angular (v8.x) web-app

### What you did
I have the extension installed, I opened up the dev tools, there is the following error message:

`Uncaught SyntaxError: Identifier 'eventMap' has already been declared` (dom-testing-library-event.js:1)

If I disable the extension in the chrome settings, the error goes away. If I enable it again, guess what? The error appears again. Please see the attached screenshot below

![image](https://user-images.githubusercontent.com/23277526/85857550-608ee900-b7ba-11ea-9edc-459b48d85c51.png)

xoxo

### What happened
There is an error thrown out into the console

### What you expected to happen
No error in the console

**Comment by litti** [comment]
This error is still present in Passbolt Extension, v3.1.0. When will it be fixed finally?

**Comment by stripthis** [comment]
We'll bump it in our backlog. Please bear with us, we have hundred of issues open.

**Comment by stripthis** [comment]
Ref. PB-6074

**Comment by Benj1er** [comment]
@felvct @litti Is this error still present in Passbolt Extension, v3.2.2 ?

Could you tell us what are the steps to reproduce this error ?

Thank you

**Comment by cedricalfonsi** [comment]
Fixed with v3.3.0.
