### ISSUE TITLE
Chrome extension does not allow to copy/unhide password (with API v2.4.0)

### ISSUE THREAD

**Issue by EtronikaVytas** [passbolt/passbolt_browser_extension#102]
Version: 2.13.4
Chrome: 83.0.4103.116

Local hosted Passbolt with Chrome browser does not allow to copy/unhide password. Previously it used to work, until latest Chrome updates.
No errors in frontend, only warning:
DevTools failed to load SourceMap: Could not load content for chrome-extension://didegimhafipceonhjepacocaffmoppf/data/vendors/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by cedricalfonsi** [comment]
Hello @EtronikaVytas,

Can you confirm me you are running the latest version of the API v2.13.1?

**Comment by EtronikaVytas** [comment]
Where could I find it?

**Comment by cedricalfonsi** [comment]
You can point your mouse on the ❤️ in the footer of the application.
The first number is relative to the API version.

**Comment by EtronikaVytas** [comment]
Thank you. it is 2.4.0. So we will update it and retest.

**Comment by EtronikaVytas** [comment]
Confirmed - issue closed.
