### ISSUE TITLE
Passbolt hangs when try to paste credentials

### ISSUE THREAD

**Issue by burasuk** [passbolt/passbolt_browser_extension#104]
## Passbolt hangs when try to paste credentials
* Passbolt Version: 2.13.5
* Platform and Target: 
-- Browser: Firefox 79 (64bit)
-- etc.: Windows 10, 64 bit

### What you did
I'm try to log thru passbolt, but when i click "use on this paste" it hangs on spinner and nothing is happened.
When i tries again, it's the same.

### What happened
Hangs on spinner and nothing is happened. Did not paste credentials.
Console in passbolt extensions show no errors.
Server has response correctly for: https://example.com/resources/9d7e2e7e-....json?api-version=2&contain[secret]=1

It happend very often(dozens of times). Especially on Firefox.

![passbolt_hangs](https://user-images.githubusercontent.com/7629077/89520303-f4060180-d7dd-11ea-8a5c-c519db80507a.png)

### What you expected to happen
Paste credentials on page.

**Comment by stripthis** [comment]
See also: https://community.passbolt.com/t/autofill-is-unreliable/2860

**Comment by cedricalfonsi** [comment]
@burasuk I'm closing this task has it seems to have been fixed. Feel free to reopen the issue if you are still encountering it.
