### ISSUE TITLE
Scenario: passphrase seems to not be working when space and/or new line characters copied

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_browser_extension#111]
## Passphrase seemed to not be working every time
I consider this a bug in the user experience flow.

### What you did
I emailed myself the passphrase to install my key on a new computer. It seemed there was a problem with the passphrase sometimes being accepted and sometimes not. I was double-clicking on the passphrase in the body of the email, copying, and trying both right-click "paste" and CTRL-V to paste. It would sometimes work, but mostly not.

### What happened
This may not be common but here's a possible unsolved example: https://community.passbolt.com/t/passphrase-not-working/3163/6

It turns out that when I was copying my passphrase, it was picking up either a space or new line character in the process (invisible to me, and I'm still not certain what it was). I only discovered this when I pasted into Notepad and saw it created two new lines and then the passphrase. I then tried putting in the correct passphrase, adding spaces in the front, and it threw an error. Just like Remy suggested in the post above, "maybe there was a leading/trailing space".

Technically, it was not the correct passphrase, but this scenario may be invisible to the user and could cause issues. When I inspected the raw email code, the body of the email started with a blank line. This must have been what was copied with the passphrase, even though the blank line was not rendered.

Are spaces in passphrases permitted? If not, then if spaces or new lines precede or follow the passphrase, maybe there should be a trim function, and also a check in the passphrase creation process for any space character \n or \r\n kind of sequence in the beginning or end.

### What you expected to happen
To be able to copy/paste from a web page or document. _**Since I cannot see the password**_ I am pasting into the field with a show password "eye" it took me awhile to verify what was getting pasted, even though the passphrase was correct the whole time.

**Comment by stripthis** [comment]
This is not really a bug, but a change request to add a "view passphrase" button on the passphrase input. 
I think it makes sense, you can create a request on the community forum for this.
