### ISSUE TITLE
Profile badge is not displaying correctly (showing ... instead of email/ name) [SOLVED]

### ISSUE THREAD

**Issue by JosephGarrone** [passbolt/passbolt_browser_extension#113]
## Loss of User Interface Permissions
* Passbolt Version: 2.13.5
* Platform and Target:
-- Browser: 88.0.4324.104 (Official Build) (64-bit) (cohort: 88_96_win)
-- Extension: 3.0.0

### What you did
Nothing, extension auto-updated.

### What happened
Can't see my username and email(?) - can't recall if it was email.
![image](https://user-images.githubusercontent.com/4310797/105950306-dee99b80-60b9-11eb-910d-662d38713ab1.png)
This is probably likely related to the following errors that now appear in console:
![image](https://user-images.githubusercontent.com/4310797/105950404-135d5780-60ba-11eb-8c87-029edf59fd7a.png)

I can also no longer access the administration side of things, nor view any user configuration items. It seems very much like the UI has no notion of what level of access I have. Luckily I do still seem to be able to access passwords. Everytime I click the "Users" tab I generate another identical console error as per above.

### What you expected to happen
Whatever was there before to appear.

### What did you try?
- Tried clearing all site data from dev tools in Chrome
- Tried the usual Ctrl/Shift F5 refresh
- Tried re-logging

**Comment by stripthis** [comment]
@JosephGarrone thank you for the bug report. 
Can you open up what is listed under "details" in the error?

Also if you are the administrator on the server can you run:
```
sudo -H -u www-data bash -c "./bin/cake passbolt datacheck --hide-success-details" 
sudo -H -u www-data bash -c "./bin/cake passbolt cleanup --dry-run"
```

**Comment by JosephGarrone** [comment]
As request, under details:
![image](https://user-images.githubusercontent.com/4310797/105951259-78657d00-60bb-11eb-8e77-3a10c6a0e0b0.png)

```
sudo -H -u www-data bash -c "./bin/cake passbolt datacheck --hide-success-details" 
```
![image](https://user-images.githubusercontent.com/4310797/105951432-bc588200-60bb-11eb-9e83-03890a2657c9.png)

```
sudo -H -u www-data bash -c "./bin/cake passbolt cleanup --dry-run"
```
![image](https://user-images.githubusercontent.com/4310797/105951480-d1351580-60bb-11eb-9c2d-a3574c31aa88.png)

I should note that we haven't performed any server changes since probably around August 2020 when we updated to the latest release.

**Comment by stripthis** [comment]
@JosephGarrone seems you have some issues with your data, e.g. some groups that were removed manually in the Database but group memberships are still present.  Can you please run the later to see if this fix your issue?
```
sudo -H -u www-data bash -c "./bin/cake passbolt cleanup"
```

**Comment by JosephGarrone** [comment]
We're using LDAP synchronisation, so all group editing would have been done on the AD side. That has cleared up this issue. Any idea how this could occur with only an extension update?

**Comment by stripthis** [comment]
@JosephGarrone the new version of the extension is stricter with the validation of the data, to provide security in depth. That's why you're seeing this issue, basically the extension didn't trust your profile associated data, because data was not clean.

We'll investigate what your describing is possible (groups are deleted but not membership when using AD synchronization), but generally this happens when group data is deleted manually.

**Comment by JosephGarrone** [comment]
Ah yep makes sense. Thanks for the quick resolution!

**Comment by stripthis** [comment]
Ref. https://community.passbolt.com/t/profile-badge-is-not-displaying-correctly-showing-instead-of-email-name-after-v3-update/3466/2

**Comment by stripthis** [comment]
Publishing another hotfix for these issues.
Please check: https://community.passbolt.com/t/browser-extension-v3-0-0-data-issues-identified-for-users-using-passbolt-since-v1/3471
