### ISSUE TITLE
C'ant display users tab and password tab bug too

### ISSUE THREAD

**Issue by PeanutStick** [passbolt/passbolt_browser_extension#114]
## C'ant display users tab and password tab bug too
* Passbolt Version: 3.0.0
-- Browser: Firefox 78.5.0esr (64 bits)

### What you did
Yesterday I was able to create new users and add them to groups.

### What happened
I can't create or see users, the loading bar is stuck.
I have this error in the console.
`Uncaught (in promise) 
Object { fileName: "moz-extension://bd1ce3a1-04e3-4945-abab-9ee33d0b7734/index.min.js", lineNumber: 11700, columnNumber: 5, message: "Could not validate entity GroupUser.", name: "EntityValidationError", details: {…} }

I can't click on boutons ,copy, edit, share, export and more in the Passwords tab.

Uncaught (in promise) 
Object { fileName: "moz-extension://bd1ce3a1-04e3-4945-abab-9ee33d0b7734/index.min.js", lineNumber: 11700, columnNumber: 5, message: "Could not validate entity GroupUser.", name: "EntityValidationError", details: {…} }

Uncaught (in promise) 
Object { fileName: "moz-extension://bd1ce3a1-04e3-4945-abab-9ee33d0b7734/index.min.js", lineNumber: 11700, columnNumber: 5, message: "Could not validate entity GroupUser.", name: "EntityValidationError", details: {…} }`

### What you expected to happen
I need help to solve the problem 
![New Issue · passboltpassbolt_browser_extension - Mozilla Firefox_2](https://user-images.githubusercontent.com/38986405/105973642-4a694400-608d-11eb-8fdb-3a0cc902f817.png)

**Comment by nourcy** [comment]
Hi @PeanutStick,

Do you have access to the server? if so can you paste the result of the following commands please:
```
sudo -H -u www-data bash -c "./bin/cake passbolt datacheck --hide-success-details" 
sudo -H -u www-data bash -c "./bin/cake passbolt cleanup --dry-run"
```

**Comment by GGracieux** [comment]
same here since this morning.

**Comment by nourcy** [comment]
Hi, I have posted a message in the community forum of passbolt
https://community.passbolt.com/t/browser-extension-v3-0-0-issues-identified-for-v1-data/3471
We will close the post here to centralise.

**Comment by stripthis** [comment]
Publishing another hotfix for these issues.
Please check: https://community.passbolt.com/t/browser-extension-v3-0-0-data-issues-identified-for-users-using-passbolt-since-v1/3471

**Comment by Crash-Zeus** [comment]
Firefox extension version 2.13.8 :
![Screenshot_20210127_145822](https://user-images.githubusercontent.com/44286581/106002862-e6a54200-60b1-11eb-9dbf-c5e00c8674a2.png)

Firefox extension version 3.0.0 & 3.0.1 :
![Screenshot_20210127_150134](https://user-images.githubusercontent.com/44286581/106003057-1d7b5800-60b2-11eb-9e02-aa12ce48d69b.png)

Same problem on chrome & chromium.
Us passbolt run on version docker 2.13.5
