### ISSUE TITLE
The extension does not work in chrome after the update

### ISSUE THREAD

**Issue by AnswerKAS** [passbolt/passbolt_browser_extension#117]
## The extension does not work in chrome after the update

* Passbolt Version: 2.7.1
* Platform and Target:
-- Browser: Chrome 86.0.4240.198 
* SERVER INTO
-- Debian 9.13
-- PHP 7.0.33-0+deb9u10 (cli) (built: Oct  6 2020 17:08:28) ( NTS )
-- Server version: Apache/2.4.25 (Debian)
-- Server built:   2019-10-13T15:43:54
-- mysql  Ver 15.1 Distrib 10.1.47-MariaDB

### What you did
After updating the extension, the password cannot be shared

### What happened
1) When I go through the extension, the page takes a long time to load. Page loading can take 30 seconds. Also in the developer tools in chrome, an error appears. This is part of the error: **"stack:" Entityvalidationerrors: Could not validate entity G...mhafipceonhjepacocaffmoppf/index.min. js:10142:26)", message: "Could not validate entity GroupUser.", name: "EntityValidationError", details: {…}"**
2) When you try to log in to my profile, the information about me is not reflected. User name, phone number, email, etc.
3) And most importantly, when I try to share the password, the page freezes and does not respond to any actions.

### What you expected to happen

To check, I tried to delete the extension. After deleting the problem disappeared

**Comment by AnswerKAS** [comment]
Here's what happens when you try to share your password
![passbolt](https://user-images.githubusercontent.com/33487015/106120943-90a3cd80-6189-11eb-97ec-7ee21ead2fc2.png)

**Comment by nourcy** [comment]
Hi @AnswerKAS ,

Did you try to perform a cleanup on your instance?
`sudo -H -u www-data bash -c "./bin/cake passbolt cleanup --dry-run"`

Thanks

**Comment by stripthis** [comment]
Closing as duplicate. https://community.passbolt.com/t/browser-extension-v3-0-0-data-issues-identified-for-users-using-passbolt-since-v1/3471
