### ISSUE TITLE
"Get the plugin" does not recognise installed plugin after retry. Unable to sign up new users.

### ISSUE THREAD

**Issue by sblandford** [passbolt/passbolt_browser_extension#118]
* Passbolt Version: 2.13.5 on server, [3.0.5] - 2021-02-03 plugin
* Platform and Target:
-- Browser: Tried Firefox, Chrome and Edge on Windows 7 & 10
-- Web server: nginx-1.18.0-1.41.amzn1.x86_64, php71-fpm-7.1.33-1.43.amzn1.x86_64 

### What you did
Created a new user and send invite

### What happened
Two different new users complained that after having installed the plugin and pressing "Retry", the request to install the plugin remained even though the plugin was definitely installed. They were both using Chrome on Windows, I asked them to try Firefox but the result was the same. I also tried this locally on Win10/MS Edge and hit the same problem. It is 100% repeatable as far as I can tell.

If the browser is directed at the index URL instead of the invite URL, the message is displayed that the plugin _is_ installed but is not configured.

### What you expected to happen
Next step of sign up procedure, "Define your keys" should become available once the plugin is installed.

**Comment by cedricalfonsi** [comment]
Hello @sblandford,

Sorry to read that some of your users are experiencing an issue to setup the browser extension.
Unfortunately we are unable to reproduce the issue on our side with our automated tests as well as manually.

In order to narrow the issue, could you please provide us with more information.
To start a screenshot of the output of the console of the browser extension. You can open the browser extension debug tool as following:
-- Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
-- Chrome: https://stackoverflow.com/a/10258029/4063145

**Comment by sblandford** [comment]
Hi @cedricalfonsi,

I didn't post any console output because there is no console output in the browser. However I am seeing an error on the server error log:

```
2021-02-08 16:18:14 Error: [Cake\View\Exception\MissingTemplateException] Template file "/Setup/json/start.ctp" is missing. (/var/www/html/passbolt/vendor/cakephp/cakephp/src/View/View.php:1583)
Request URL: /setup/install/5b4d6c7a-698d-4de6-94a3-db7135d20fb3/17b1abdc-0cea-4daa-afbb-39ed196f35a2.json?api-version=v2
```
I had assumed the problem was with the plugin because the last API update was last August and the last plugin update was a few days ago. I did update the API a few weeks ago and it is quite likely I haven't created any new users since then until now. 

It looks like I raise the issue in the wrong project. I suggest closing this ticket. I will see if I can fix the API problem myself (all the health checks show green) and raise it on the community forum if I can't figure it out.

Thanks for your help.

**Comment by sblandford** [comment]
Plugin was not at fault.
