### ISSUE TITLE
Non latin1 CSV import not working

### ISSUE THREAD

**Issue by flifloo** [passbolt/passbolt_browser_extension#125]
## Non latin1 CSV import not working
* Passbolt Version: 3.2.1.
* Platform and Target:
-- Browser: Vivaldi 3.8.2259.42 & Firefox 88.0.1
-- Web server: passbolt-pro-server/buster 3.1.0
-- etc.: Tested on Arch Linux & Windows 10

### What you did
Import a KeePass CSV with UTF-8 characters.

### What happened
Nothing, the button import do nothing.

Some browser console log:
![Clipboard - 26 mai 2021 15_16](https://user-images.githubusercontent.com/12417808/119674993-f1dc6480-be3c-11eb-82bb-07d1690d3509.png)

### What you expected to happen
The start of the import

### Other
I build an older version of the browser extension and I can import without any problem.
Furthermore, this morning I was able to import and the afternoon I can't, so I guess the new version make 6h ago can be blamed.
And if I encode all UTF-8 chars to make a latin1 CSV I can import (but I loos all UTF-8 chars).

**Comment by stripthis** [comment]
Hi @flifloo, we'll investigate and come back with a fix. Thanks for the report.

**Comment by Benj1er** [comment]
Hi @flifloo, the fix has been deploy on Passbolt v3.2.3.
