### ISSUE TITLE
Ghosting in-form-icon

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_browser_extension#129]
## Ghosting in-form-icon
* Passbolt Version: 3.3.1
* Platform and Target:
-- Browser: FF dev 94
-- Web server: Nginx

### What you did
Signed into a site without using Passbolt extension, and extension QuickAccess is inactive (not signed into Passbolt). The site had a sign in modal, and I entered credentials. Once credentials are entered into the fields, there is no action seen being taken by the extension. The modal disappears after authentication.

### What happened
From the modal log in form location on the screen, after Login button on the modal was clicked, the iframe is seen being created in the DevTools Inspect, and the `in-form-icon` is still showing:

![image](https://user-images.githubusercontent.com/47018474/139124398-ac930367-5b2e-4e88-80e1-cc6a7f80dbac.png)

Html shown in this section is:
![image](https://user-images.githubusercontent.com/47018474/139124628-f76726f9-7487-412a-9e16-cc3c5f0c1892.png)

### What you expected to happen
I would expect if the form never showed the icon, that it would not appear after the fact. Or, that if the element it is associated with no longer exists, that the icon would no longer appear as well.

**Comment by Tabiskabis** [comment]
Apparently the change that brought the icon+auto-fill also kinda borked one of our non-public websites, that uses a ridiculous amount of forms internally as some compatibility hack for no-javascript IE 6. Least I overheard collegues complain about how rendering on that site has slowed down tremendously lateley, and another one mentioned that he temporarly worked around the issue by disabling passbolt plugin. 
Again sorry, I can't name a public URL. However i suspect there's a quadratic algorithm involved in the new code.

**Comment by garrettboone** [comment]
@cedricalfonsi This seems to be fixed as a result of changes in 3.4. I will close, thanks.
