### ISSUE TITLE
Autofocus the password field on login

### ISSUE THREAD

**Issue by EliotBerriot** [passbolt/passbolt_browser_extension#13]
At the moment, when you click on the extension in Firefox, you are redirected to your password server but the login form is actually shown by the browser extension. 

The email field is prefilled on my installation, but I have to manually click the password field and enter the password each time I want to login. I think at least the password field should be autofocused by default on the page load, to avoid that extra click.

I never contributed to this project but I'm okay to take some time to submit a PR if you want.

**Comment by stripthis** [comment]
That would be a nice improvement, feel free to submit a pull request for this. As discussed in the #14 the trick is that the passphrase is in an iframe controlled by the plugin. @kevinmuller can explain how we handle focus control in this case (he did something similar in src/all/data/js/masterPassword/masterPassword.js )

**Comment by stripthis** [comment]
Duplicate with: https://community.passbolt.com/t/as-a-user-on-the-login-screen-or-master-password-dialog-my-cursor-should-get-auto-focused-on-the-password-field/50
