### ISSUE TITLE
CTA icon is offset when body position is not zero

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_browser_extension#130]
## CTA icon is offset when body position is not zero
* Passbolt Version: 3.3.1.
* Platform and Target:
-- Browser: FF dev 94
-- Web server: Nginx

### What you did
I have a Roundcude login form, and the CTA icon is offset when field position is calculated:
![image](https://user-images.githubusercontent.com/47018474/139253159-713f325a-11e9-4fba-a798-bfee17d213cc.png)

### What happened
I checked the styleguide calculations and it seems to be based off of the body element.
`document.body.getBoundingClientRect()` returned `x: y:120`. I manually removed the margin in the form element which caused the body to be at zero. Icon is properly placing:
![image](https://user-images.githubusercontent.com/47018474/139253407-d1949f55-223a-4753-9c06-3c424094ab15.png)

### What you expected to happen
Icon magical placement.

**Comment by cedricalfonsi** [comment]
Hi @garrettboone,

Thanks for the report.
We scheduled to work on a fix , we'll publish it with the next v3.3.2 release.

Best,
Cédric

**Comment by cedricalfonsi** [comment]
Fixed with v3.4.0
