### ISSUE TITLE
V3.3.1 extension don't work in chrome

### ISSUE THREAD

**Issue by cerberek** [passbolt/passbolt_browser_extension#134]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to an installation: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt Browser Extensions.
For passbolt API, docker, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new Browser Extension bug please use the following format:

## ISSUE NAME
* Passbolt Version: 3.3.1
* Platform and Target:
-- Browser: Chrome 96.0.4664.45 on Ubuntu
-- Web server: Self hosted behind nginx
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
Since version 3.3.0 become passbolt extension unusable in Chrome, I did upgrade of our self hosted passbolt to version 3.3.0-1. It helped little, but it was still useless.
So I removed passbolt extension, install it again and now I don't have even option to connect to our server.
Click on extension shows me https://www.passbolt.com/start instead of popup window as before

### What happened
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

**Comment by garrettboone** [comment]
@cerberek When you uninstalled the extension it became no longer associated with your passbolt site. You will need to navigate directly to your passbolt site and begin the recovery process for your account. Please define "unusable" and remember github is only for bugs. Problems and questions with use or installation are handled in the forum.

**Comment by cerberek** [comment]
OK, so my passbolt page don't load on chrome now. It had problems before I removed extension, but now it just laod empty HTML with 
<html class="passbolt no-js version launching no-passboltplugin" lang="en"><head>
    <meta charset="utf-8">
    <title>Passbolt | Open source password manager for teams</title>
    
<div id="container" class="page ">
<div class="temporary skeleton">
    <div id="container" class="page password">
        <div class="header first">
            <nav><div class="primary navigation top"></div></nav>
        </div>
        <div class="header second"></div>
        <div class="header third"></div>
        <div class="panel main"></div>
    </div>
    <footer>
        <div class="footer"></div>
    </footer>
</div>
</div>
</body></html>
        <div class="footer"></div>
    </footer>
</div>

**Comment by stripthis** [comment]
Most likely this is an issue related to your installation, such as data integrity issue.
Can you open an issue on the community forum under "installation issue" with the relevant information? 

Otherwise please provide the information:
- relevant information about my server (component names and versions, etc.)
- a copy of the webextension logs
- a copy of the logs and healthcheck
- a copy of the data cleanup task

Cheers,

**Comment by garrettboone** [comment]
@cerberek I could not reproduce this problem. Extension logs are mentioned in this post [here ](https://community.passbolt.com/t/white-page-displayed-after-ldap-infos-have-been-added/3986/2)on the forum site. Post on the forum if you need more help.
