### ISSUE TITLE
fixed z-index value of 1000 - results in hidden icon for elements with higher z-index value

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_browser_extension#137]
Example: https://my.caresource.com/login which has a modal login. The  page's `modal` class is set to z-index of 1050. z-index of 1000 is not enough.

Not sure if a value higher than 1000 is a better solution, but that would fix it in this case.

**Comment by stripthis** [comment]
Hi @garrettboone thanks for the report, we'll have a look.

**Comment by cedricalfonsi** [comment]
Fixed with v3.5
