### ISSUE TITLE
Shortcuts are broken in the passphrase form

### ISSUE THREAD

**Issue by EliotBerriot** [passbolt/passbolt_browser_extension#14]
When you want to copy a password, you are prompted with the following modal:

![screenshot from 2017-02-22 14-18-05](https://cloud.githubusercontent.com/assets/1970915/23213087/e0ee3740-f909-11e6-94fd-e59f885aec39.png)

The problem is that you cannot use classic form shortcuts such as `tab` to move to the next form field. When you hit `tab`, the focus goes to to the three-letters hint ont the right of the field, instead of what you would expect, to the `remember for 5 minutes` checkbox. If you press `tab` again, the focus is back to the password field, which is counter-intuitive.

When I have to fill such forms in other apps/website I usally do:

1. Fill the password
2. Press `tab`
3. Press `space` to toggle the checkbox
4. ` Press `Enter` to submit the form

It means I can use my keyboard only to do the job, which is both faster and more convenient to me. Here I have to:

1. Fill the password
2. Click to toggle the checkbox
3. Click to toggle the submit form

As you can see, I cannot do that without involving the mouse.

I think one way to adress this would be to make the whole thing a real form, including the password field, the checkbox and the submit button.

**Comment by stripthis** [comment]
Hi Eliot,

That would be a nice improvement indeed, functionally what you describe makes sense. The only issue with what your are proposing is in the technical approach. 

Currently the password input field (and the token) are in a separate iframe for security reason (to prevent a malicious script running on the page to access the passphrase), so it would not be possible to have the password, checkbox and submit button as part of the same form per say. It should be possible to implement what you describes (e.g. going out of the iframe and selecting the checkbox element).

Cheers,

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.3
