### ISSUE TITLE
Firefox Passbolt off edge of window 

### ISSUE THREAD

**Issue by jscott304** [passbolt/passbolt_browser_extension#145]
* Passbolt Version: 3.5.0
* Platform and Target:
-- Browser: Firefox 98.0 (64-bit)
-- Web server: Passbolt Docker

### What Happened
When clicking on the passbolt icon in the user entry field the passbolt popup goes past the edge of the browser screen.

### What I Expected to Happen
If user / password entry boxes are near the edge of the screen to shift the passbolt popup to fit within the browser. Example Below.

![Capture](https://user-images.githubusercontent.com/24324316/157714365-9f7c6b0d-3351-48cc-8fc9-9cd9eb58b3e7.PNG)

**Comment by AnatomicJC** [comment]
Hi @jscott304 and thanks for reporting this to us 👍 

We created an internal ticket to fix this under reference PB-14174. We will keep you posted as soon as the fix will be published.

With best regards,

**Comment by Benj1er** [comment]
Fix with v4.0.0 don't hesitate to reopen it if the issue persists.
