### ISSUE TITLE
Plugin not recognized by browsers for new users after update

### ISSUE THREAD

**Issue by starlessboi** [passbolt/passbolt_browser_extension#153]
Plugin not recognized by browsers for new users after update
* Passbolt Version: 3.6.0-1-ce
* Platform and Target: 
-- Browser: Chrome/FireFox
-- Web server: proxied by Haproxy
-- Platform: Docker

What you did
After docker image updated to latest version, new users can not register  any more (for first time), but users who have activated before update, working normally

What you expected to happen
New users should be able to register

**Comment by AnatomicJC** [comment]
Hi @starlessboi,

Maybe are you affected by this issue: https://community.passbolt.com/t/user-cannot-signing-after-v3-6-upgrade-docker/5416 ?

Can you have a look and let us know ? If you encounter a different issue, can you create a new thread on community forum ?

Cheers,

**Comment by starlessboi** [comment]
Hi @AnatomicJC 
Thanks, it was the same
But, according to this tutorial: https://help.passbolt.com/faq/hosting/how-to-rotate-server-gpg-keys?pk_vid=cb84e7a8f553248816559047086cbe75
after removing keys, restarting the container did not worked, I had to: docker compose up -d --force-recreate the container to take affect the changes.
thanks

**Comment by AnatomicJC** [comment]
Thank you for your feedback and for the `--force-recreate` additional parameter, it makes sense.
I will create an internal ticket to update the documentation.

Best,

**Comment by cedricalfonsi** [comment]
The help site was updated accordingly. Thanks for your contribution @starlessboi
