### ISSUE TITLE
In-form integration doesn't always display passbolt icon in credentials fields

### ISSUE THREAD

**Issue by cedricalfonsi** [passbolt/passbolt_browser_extension#159]
* Passbolt Version: 3.7.3
* Platform and Target: Firefox 106 / Chrome 107
* Forum reference: https://community.passbolt.com/t/auto-save-dialog-box-dont-show-up/5970
* Internal tracker reference: PB-19662

### What you did

1. Navigating to https://librairie-energies-renouvelables.org
2. Clicking on connection
3. Clicking on a credential field

### What happened

In-form integration doesn't display passbolt icon in credentials fields. Refreshing the page makes it work.

### What you expected to happen

In-form integration to display passbolt icon in credentials fields.

**Comment by Benj1er** [comment]
Fixed with v4.1.2, don't hesitate to reopen it if the issue persists.

**Comment by Benj1er** [comment]
Fixed with v4.1.2, don't hesitate to reopen it if the issue persists.
