### ISSUE TITLE
Cannot stop Chrome from starting up with the OS (macOS) because of the Passbolt add-on

### ISSUE THREAD

**Issue by belkone** [passbolt/passbolt_browser_extension#161]
## Cannot stop Chrome from starting up with the OS (macOS) because of the Passbolt add-on
* Passbolt Version: 3.7.3
* Platform and Target:
-- Browser: Chrome 107.0.5304.87 on macOS 13.0 (22A380)

### What happened
After installing the Passbolt add-on for Chrome, it is not possible to disable Chrome from starting at system startup.
After disabling autorun and re-enabling Chrome, the autostart is set again and you can do it over and over again. Always the system setting will be restored after restarting Chrome. The only solution is to disable the Passbolt extension in Chrome, then everything with Chrome's autostart at system startup works as it should.

### What you expected to happen
No effect of Passbolt extension on Chrome autostart

**Comment by stripthis** [comment]
Thanks for the report @belkone, we'll investigate.

**Comment by belkone** [comment]
@Benj1er thanks for the information :)
Meanwhile a new version of Chrome came out but didn't fix anything ^^ (since 2012 as you rightly noticed).
Your solution seems to work ;) 
If it's not an issue directly related to the plugin I guess we can close this issue. thanks!
