### ISSUE TITLE
username is not automatically set in input field with name username

### ISSUE THREAD

**Issue by batmartin** [passbolt/passbolt_browser_extension#173]
## ISSUE NAME
* Passbolt Version: 3.10
* Platform and Target:
-- Browser: Chromium Version 110.0.5481.104 (64-Bit)
-- Plugin Version 3.11.2

### What you did
Configured username and password in passbolt for a specific (company internal) site and used the autofill functionality.

### What happened
Only password is filled out. Username remains empty.

### What you expected to happen
Username should also be filled out automatically.

This is how the form html looks like:

```
<form class="user" method="post" action="/login/Emergency%20Access">
                      <input type="hidden" name="then" value="---removed---">
                      <input type="hidden" name="csrf" value="---removed---">
                      <div class="form-group">
                        <input autofocus="autofocus" type="username" name="username" class="form-control d-inline" style="width:50%;" placeholder="Username">
                      </div>
                      <div class="form-group">
                        <input type="password" name="password" class="form-control d-inline" style="width:50%;" id="exampleInputPassword" placeholder="Password">
                      </div>
                      <button type="submit" class="btn btn-dark" style="width:50%;">
                        Login
                      </button>
                    </form>```

**Comment by Benj1er** [comment]
Hello @batmartin,

Actually the type "username" is not an expected standard value.
Checkout the documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-type

If you replace it with a type="text" the field should be detected.

Best regards

**Comment by garrettboone** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

@batmartin `autocomplete` has a "username" option, maybe this is the intended attribute.
