### ISSUE TITLE
Passbolt icon not removed after signing in within an iframe in the Brave browser on Mac

### ISSUE THREAD

**Issue by APIANT** [passbolt/passbolt_browser_extension#175]
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.

We're using the Docker version

You don't have a better way to show your version info than this?
![image](https://user-images.githubusercontent.com/2120558/225993022-0a94d29d-89cb-40b7-bb27-6cf590c34b5e.png)

* Platform and Target:
-- Browser: NAME AND VERSION

Brave on Mac
![image](https://user-images.githubusercontent.com/2120558/225993091-2e93d764-9dc2-4e09-adbe-88d4932dba09.png)

-- Web server: NAME AND VERSION
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
EXPLAIN WHAT YOU DID, PREFERABLY WITH CODE EXAMPLES, HERE.

We load the Hazelcast management console within an iframe in our admin console:
![image](https://user-images.githubusercontent.com/2120558/225993540-460835c3-03cb-4d1a-9b81-035082214ff3.png)

Then we sign in normally without using passbolt.

### What happened
EXPLAIN WHAT IS ACTUALLY HAPPENING, HERE.

The passbolt icon remains onscreen after the signin and won't go away:

![image](https://user-images.githubusercontent.com/2120558/225994228-27459351-84a4-48b4-813e-dcc0316d160a.png)

The icon even remains visible when the iframe containing the Hazelcast console is hidden:
![image](https://user-images.githubusercontent.com/2120558/225994408-29ced4c7-4981-4668-8f29-282130f1f8aa.png)

### What you expected to happen
EXPLAIN WHAT IS TO BE EXPECTED, HERE.

The icon should disappear after signing in.

Did a quick test, does not happen in Firefox on Mac.

**Comment by Benj1er** [comment]
Hello @APIANT,

Is this issue still remain on the last Passbolt version ?
Please let us know if a fix should be done.

Thank you

**Comment by APIANT** [comment]
Hi, I am currently on vacation and unable to confirm.  I do believe the problem still happens, however.

Will confirm and provide details either late this week or early next.

**Comment by APIANT** [comment]
Hi, I have confirmed the problem persists:

![image](https://github.com/passbolt/passbolt_browser_extension/assets/2120558/f74c7af6-454e-4dc0-91d8-2620616a35b2)

The hazelcast content is loaded into an iframe.

I upgraded our passbolt version recently, too:

![image](https://github.com/passbolt/passbolt_browser_extension/assets/2120558/907de163-c84d-4794-8d77-2492577bc99c)

Let me know if you need more info!

**Comment by Benj1er** [comment]
Hi @APIANT,

Thank you for your feedback.

Could you provide us the source code of the page?

Be very careful to make sure there's no private or sensitive data on the page before copying the source code.

Thank you

**Comment by APIANT** [comment]
Unfortunately no.

It is a single-page app that dynamically creates the DOM, there is no HTML I can provide that would serve as a test case from my screenshots.

**Comment by Benj1er** [comment]
Even if it's a single-page app  that dynamically creates the DOM, you can access of the generated DOM from your browser.

You can right-click on the page and click on the "View Page Source" item. This action should open a new page with the source code, which you can then copy and paste into a file.

Thank you

**Comment by APIANT** [comment]
Sorry, that doesn't work.  The page source only contains the wrapper HTML for the SPA, not the DOM content.

**Comment by Benj1er** [comment]
Fixed with v4.4.0, don't hesitate to reopen it if the issue persists.
