### ISSUE TITLE
Error where a Password confirm is on the same page as a new password field

### ISSUE THREAD

**Issue by DOClearwater** [passbolt/passbolt_browser_extension#176]
##Title: Error where a Password confirm is on the same page as a new password field
* Passbolt Version: 3.12.0
* Platform and Target:
-- Browser: Chrome: Version 111.0.5563.65 (Official Build) (64-bit)
-- Web server: 3.11.0

### What you did
Went to change password on an account (Amazon). I utilized the passbolt UI element on the "new password" field to generate a password.  It also filled in the "old Password" field and the "confirm new password field" (all 3). After retyping in the proper old password and submitting Passbolt asked to save the old password not the new one which resulted in not having the new password that it was changed to and will have to perform a password reset. This seems somewhat problematic in my view.  

### What you expected to happen
I expected that Passbolt would save the password it recommended not the Old password.

**Comment by Benj1er** [comment]
Hello @DOClearwater,

Thank you for your report.

A follow-up ticket was created on the internal tracker: PB-25865

**Comment by Benj1er** [comment]
Fixed with v4.4.0, don't hesitate to reopen it if the issue persists.
