### ISSUE TITLE
How and where the private key is stored?

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_browser_extension#18]
See. https://twitter.com/kwisarts/status/841972431573155841
Add answer to the FAQ

**Comment by stripthis** [comment]
At the moment the private key is stored in the chrome.storage with storage.sync disabled. See. https://developer.chrome.com/extensions/storage

**Comment by lsmith77** [comment]
can you detail a bit more where the private key is stored? trying to recover it from a backup of my home dir.

**Comment by cedricalfonsi** [comment]
It depends on your OS and browser. 

Take a look at this community forum ticket, it is relative to what you are looking for: [https://community.passbolt.com/t/recover-private-key-from-disk-image/1412/2](https://community.passbolt.com/t/recover-private-key-from-disk-image/1412/2)
