### ISSUE TITLE
ErrorNotFound with v4.0.0

### ISSUE THREAD

**Issue by MvrckTheBald** [passbolt/passbolt_browser_extension#183]
* Passbolt server version: 2.10.0
* Passbolt extension Version: 4.0.0
* Browser : Google Chrome
* Browser Version: Version 113.0.5672.92 (Official Build) (64-bit)
* Platform and Target: Ubuntu 22.04 

After the update, the extension stopped working, and when clicking the button, the following message appears: ErrorNotFound. 
I even recovered the account (from the link /recover), and through this, I was able to view the web page with the list of credentials registered on Passbolt. However, I couldn't share or view the passwords because the password field was no longer present.

I've tried to install the previous version from the crx file, and it started to work again. 

We are experiencing this on both windows and linux machine, with the last release.

**Comment by Benj1er** [comment]
Hello @MvrckTheBald,

You are running a version older than v2.11.0 then the backward compatibility was broken with the v4.0.0 of the browser extension. In that case you need to upgrade your API to a version > v3.

Checkout the comment in the community forum: https://community.passbolt.com/t/passbolt-extension-chrome-notfounderror-after-v4-upgrade-testing-from-2-7-1/7405/12?u=max
 
You have also the help page to upgrade your version here: https://help.passbolt.com/hosting/upgrade
 
 Best Regards

**Comment by MvrckTheBald** [comment]
Thanks @Benj1er for your quick answer. 

I've searched online for that error but wasn't able to find the link you provided. 
I think we will proceed with the update. 

Thanks again.
