### ISSUE TITLE
Description field not encrypted if saved with browser extension

### ISSUE THREAD

**Issue by Kibubu** [passbolt/passbolt_browser_extension#184]
## Description field not encrypted if saved with browser extension
* Passbolt Version: 4.0.0
* Platform and Target: Chrome
-- Browser: Brave Browser 113.1.52.100 beta
-- Web server: Unknown

### What you did
Created an entry via browser extension popup.

1. Go to https://app.bigpicture.io/signup (I guess any site will do)
2. Enter email
3. Generate random password with passbolt
4. Don't click on signup but click on passbolt symbol and choose: `save as new credential`
5. Check the new credential on your passbolt server, the description field should not be encrypted

### What happened
There is a discrepancy between passbolts behavior regarding the encryption of the description block if credentials are created directly on the WebServer's UI or with the extension as popup. As this [forum post](https://community.passbolt.com/t/the-description-field-is-saved-now-encrypted-by-default/4273) states all new credentials should now have an encrypted description block. But all my credentials created with the extension popup have an unencrypted description block, while credentials created via the WebServer will have an encrypted description block.

### What you expected to happen
Regardless the flow the description block should always be encrypted by default. Especially since OnePass's failure Q3/Q4 2022.

This might also be an API bug, but since the extension is encrypting the credentials with my local priv key the description block should also be encrypted.

**Comment by stripthis** [comment]
Hello,

This is a known issue, I agree, with version 4 I think it's time to switch this behavior to match the main application behavior (have encrypted description by default even if they are empty). It was kept that way to optimize for backward compatibility with older API versions / clients that didn't support encrypted description.

For clarity that description is empty by default when creating credentials from the browser extension quickaccess. So the description is empty by default. 

Ref. PB-24650

**Comment by Benj1er** [comment]
Fixed with v4.4.0, don't hesitate to reopen it if the issue persists.
