### ISSUE TITLE
The passbolt browser opens with a blank page

### ISSUE THREAD

**Issue by chyff** [passbolt/passbolt_browser_extension#186]
Hi, my Google browser and Firefox open passbolt with empty pages. My passbolt plugin version is 4.0.1, which updates automatically. My paabolt is a 2:00ish version that hasn't been updated
![image](https://github.com/passbolt/passbolt_browser_extension/assets/33062193/a396e8e5-b521-465f-bb40-35ca873d96c6)
![image](https://github.com/passbolt/passbolt_browser_extension/assets/33062193/f8c144fa-2c60-469f-b9d4-8cb1f588bea7)

**Comment by garrettboone** [comment]
@chyff It's known and is related to the forum link posted in the cli repo where you posted before. The forum has instructions for how to handle this.

**Comment by chyff** [comment]
> @chyff It's known and is related to the forum link posted in the cli repo where you posted before. The forum has instructions for how to handle this.

Hello, could you please send me the specific address of this solution?

**Comment by cedricalfonsi** [comment]
If you are running an API < v3.0.0, you can checkout the [community forum](https://community.passbolt.com/t/passbolt-extension-chrome-notfounderror-after-v4-upgrade-testing-from-2-7-1/7405). If you are running an API >= v3.0.0, let us know.

**Comment by cedricalfonsi** [comment]
@chyff You might have found a solution, do not hesitate to reopen if the problem persists
