### ISSUE TITLE
Passbolt icons on forms are bugged

### ISSUE THREAD

**Issue by noriban** [passbolt/passbolt_browser_extension#187]
##IMPORTANT: PLEASE READ
If you are certain this is a new Browser Extension bug please use the following format:

## ISSUE NAME
* Passbolt Version: 4.0.4
* Platform and Target:
-- Browser: Chrome 
-- Web server: 114.0.5735.133
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
![Zrzut ekranu 2023-06-19 o 09 57 52](https://github.com/passbolt/passbolt_browser_extension/assets/63416481/db1840a2-08b5-4fde-8f4b-ed3fd0a75624)

### What happened
Passbolt icons on forms are bugged

### What you expected to happen
Not bugged

**Comment by Benj1er** [comment]
Hello @noriban,

Thank you for your report.

Could you give us more details about this problem?
What are the steps to reproduce this behaviour?
Which URL were you on?

Best regards

**Comment by noriban** [comment]
When I want to log in to google and I enter the password or leave the field empty, I press the "next" button then the icon is bugged

accounts.google.com

**Comment by noriban** [comment]
![Zrzut ekranu 2023-06-27 o 14 26 30](https://github.com/passbolt/passbolt_browser_extension/assets/63416481/2c242e53-e81f-4025-b89f-56013fa47495)
![Zrzut ekranu 2023-06-27 o 14 26 46](https://github.com/passbolt/passbolt_browser_extension/assets/63416481/d4baf110-7206-4ff5-94d9-d6fbedbdaa88)

on self hosted awx too

**Comment by Benj1er** [comment]
Hello @noriban,

Thank you for your report.
A follow-up ticket was created on the internal tracker: PB-25279

Best regards

**Comment by Benj1er** [comment]
Hello @noriban,

After some investigation, we can't reproduce this issue on our side.

Do you have any other plugins installed?
Could you provide us the source code of the page?

Do you have this problem only on accounts.google.com and on awx hosted by you?

Thanks in advance for your help.

**Comment by noriban** [comment]
I have bitwarden extension on my chrome only.

I use latest chrome 115 on MacOS M1.


It seems that only on these sites I have the bug, but sometimes it appears in self hosted proxmox.

How can i send source code of pages?

**Comment by Benj1er** [comment]
Hello @noriban,

To send the page source code, you can right-click on the page and click on the "View Page Source" item. This action should open a new page with the source code, which you can then copy and paste into a file.

You can upload the file here, but before you do, be very careful to make sure there's no private data on the page before copying the source code.

Thanks

**Comment by noriban** [comment]
is it needed?  the error is triggered on every field to enter some data, should I now give the source code of all pages?
