### ISSUE TITLE
Brave support

### ISSUE THREAD

**Issue by HLFH** [passbolt/passbolt_browser_extension#19]
Hi,

It would be great to support Brave, the browser of Brenden Eich, the creator of JavaScript.
https://github.com/brave/browser-laptop 

Thanks in advance,

**Comment by stripthis** [comment]
Any volunteers to try if passbolt works out of the following the method described there?
https://blog.brave.com/loading-chrome-extensions-in-brave/

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-use-passbolt-with-brave-browser/80
