### ISSUE TITLE
Password recommended for email search gmail.com

### ISSUE THREAD

**Issue by djkato** [passbolt/passbolt_browser_extension#191]
## ISSUE NAME
* Passbolt Version: 3.12.0
* Platform and Target:
-- Browser: Firefox 4.1.0
-- Web server: mail.google.com

Hovering over the search field makes the password icon appear, suggesting auto-fill. It's a search box, so it shouldn't be there.
![firefox_UFeoI71zGA](https://github.com/passbolt/passbolt_browser_extension/assets/25299243/8879ac47-1327-4210-b538-c3e973a6190d)

**Comment by Benj1er** [comment]
Hello @djkato ,

Thank you for your report.

A follow-up ticket was created on the internal tracker: PB-25375

Best regards

**Comment by Benj1er** [comment]
Fixed with v4.3.1, don't hesitate to reopen it if the issue persists.
