### ISSUE TITLE
unbalanced brackets in password creation screen.

### ISSUE THREAD

**Issue by OperativeThunny** [passbolt/passbolt_browser_extension#192]
This is a critical bug in my mind. My OCD is so triggered. If you go to create a new password, the boxes for selecting exactly what set of characters to use in the one with squiggly braces, square brackets, and the pipe symbol, the right square brackets are unbalanced, there is an extra right square bracket!!!!

![image](https://github.com/passbolt/passbolt_browser_extension/assets/94724830/bee8c2df-e7fa-4bea-9709-025774059e8f)

**Comment by cedricalfonsi** [comment]
Thanks for your report, indeed we cannot unsee it now ;) 
Ref: PB-25956

**Comment by Benj1er** [comment]
Fixed with v4.3.1, don't hesitate to reopen it if the issue persists.
