### ISSUE TITLE
Chrome Extention stop filling the field

### ISSUE THREAD

**Issue by psyonic69** [passbolt/passbolt_browser_extension#197]
## ISSUE NAME
* Passbolt Version: Cloud  |   Chrome Extention Version 4.3.0
* Platform and Target:
-- Browser: Chrome Version 117.0.5938.92 (Official Build) (64-bit) 

### What you did
When on the webpage I click on the passbolt ext icon, select the account that i want to login and i get a message  "Unable to use password on page. Copy and paste the information instead"

### What happened
i get a message  "Unable to use password on page. Copy and paste the information instead"
![Screenshot 2023-09-27 111430](https://github.com/passbolt/passbolt_browser_extension/assets/34266695/6dd560b6-65d0-4e89-abaf-3aebac4f2b52)

### What you expected to happen
Was supposed to fill the both field.
Try it in Firefox and work fine

**Comment by Benj1er** [comment]
Hello @psyonic69,

Thank you for your report.
This problem has been detected and fixed. It should be published on chrome today or the next day.

Best regards

**Comment by FrancoisHamonic** [comment]
Hello @Benj1er,

Is it possible to push this update to the Edge Store too ?
