### ISSUE TITLE
DevExpress Input Fields don't can submit

### ISSUE THREAD

**Issue by QDaniel** [passbolt/passbolt_browser_extension#199]
## DevExpress Input Fields don't can submit
* Passbolt Version: 4.4.0
* Platform and Target:
-- Browser: Chrome
-- Web server: https://osign.opal-consulting.com/Account/Login
-- Framework: https://js.devexpress.com/Angular/

### What you did
Try to autofill and login.

### What happened
On Autofill the username and password are filled. But it can't be submit (Field are required). The change event are not triggered. 

### What you expected to happen
Correct the set Function of the input text , the Browser can check required correctly.

**Comment by Benj1er** [comment]
Hello @QDaniel,

Thank you for your report.

A follow-up ticket was created on the internal tracker: PB-28873

Best regards

**Comment by Benj1er** [comment]
This issue has been fixed on v4.5.0.
Please feel free to reopen it if the issue persists.

Best regards
