### ISSUE TITLE
Addon doesn't install in Seamonkey

### ISSUE THREAD

**Issue by e7o-de** [passbolt/passbolt_browser_extension#20]
... would be great to have Seamonkey whitelisted as well besides Firefox :)

**Comment by stripthis** [comment]
Thank you for the suggestion @e7o-de. The next release (1.6.2) will use embed web extension, and the next one native webextension. Feel free to test them on seamonkey and let us know what kind of issues are present.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-use-passbolt-with-seamonkey-browser/79/2
