### ISSUE TITLE
Not an issue but a tip: Use the word password manager more often in your github projects

### ISSUE THREAD

**Issue by wunderkind2k1** [passbolt/passbolt_browser_extension#202]
Hi passbolt Team,

I really love you product but its really hard to find if you forget the name. One reason is that you do not use the word "password manager" in your README.md files in you project. You always only say sth like "passbolt api" or "passbolt extension". Only your github org uses the term "password manager".

This makes it even hard to find on github if you look for password managers.

This is a big tip. Hope you do sth with it.

<3

**Comment by stripthis** [comment]
Hello,

Thank you for your feedback. On this repository readme the "password manager" is mentioned 4 times. I added it to the project description as well.

Best,
