### ISSUE TITLE
Autofill no longer fires the 'input' event

### ISSUE THREAD

**Issue by Hysow** [passbolt/passbolt_browser_extension#205]
## Autofill no longer fires the 'input' event since 4.5.0
* Passbolt Version: 4.5.0
* Platform and Target:
-- Browser: Chrome 119.0.6045.199
-- Web server: Nginx
-- Frontend framework: Vue 3.3.10
-- Related commit : [PB-28873](https://github.com/passbolt/passbolt_styleguide/commit/476e102891ef6bdf5342beb310c4048f8111783b)

### What I did
I autofilled login fields with Passbolt on a Vue3 application, using recommended form input binding (based on `input` event): https://vuejs.org/guide/essentials/forms

### What happened
Only `change` event was fired

### What I expected to happen
I expected that Passbold fired the `input` event.
Seems like a regression to me, worked well before 4.5.0

**Comment by garrettboone** [comment]
Input event is not fired when the element value is changed programmatically. 

https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event

**Comment by Hysow** [comment]
> Input event is not fired when the element value is changed programmatically.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event

Behavior worked fine before 4.5.0, so what changes?

**Comment by garrettboone** [comment]
@Hysow I would use `@change` instead of `@input`, or in addition to it. It should be fine then. We wouldn't expect the `input` event to be fired, if it requires user interaction.

**Comment by Hysow** [comment]
I understand your motivations for these changes. That being said, I thought I should maybe warn you that, to my knowledge, this will make your extension incompatible with  several Vue libraries (ElementPlus, Vuetify...)

**Comment by garrettboone** [comment]
@Hysow I am not speaking for the team, and do not know of any changes but am just speaking to the matter of Event handling. I develop in Vue, and am just giving my point of view regarding how to handle the change event, as explained.

**Comment by garrettboone** [comment]
Vuetify uses Vue Event handling. Vue event handling accommodates the `@change` event, even if not listed in the examples in the documentation. How does the passbolt change break libraries?

**Comment by Hysow** [comment]
@Gamabunta57 In my opinion and according to my understanding of the behavior of an autofill. Both seem possible : You modify the contentEditable of a HTMLElement (firing an `input` event) and you commit a value change in an HTMLInputElement (firing a `change` event).

Maybe the solution is simply to simulate the user behavior by emitting the same events as manual field filling. This would ensure the same behavior in all cases.

**Comment by Hysow** [comment]
Ok I just saw that you are using `@testing-utils` to trigger the events, forget my last post :laughing: 
Maybe just replace `fireEvent.change` by `userEvent.type` do the trick ?

**Comment by Gamabunta57** [comment]
I discussed about this problem with @Benj1er this morning and he had the same idea as proposed.

So, yes, we will probably go for a `userEvent` instead, it seems to be the ideal approach so far.

**Comment by jledentu** [comment]
@garrettboone 

> Input event is not fired when the element value is changed programmatically.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Element/input_event

According to the spec, the `change` event is not fired either:

> These events are not fired in response to changes made to the values of form controls by scripts. (This is to make it easier to update the values of form controls in response to the user manipulating the controls, without having to then filter out the script's own changes to avoid an infinite loop.)
>
> https://html.spec.whatwg.org/multipage/input.html#common-input-element-events

But, since the extension simulates the user behavior, yes, both events (`input` then `change`) should be fired. So I agree that using `userEvent` is a good solution.

**Comment by Benj1er** [comment]
Hello @Hysow,

The issue has been fixed in v4.5.2, and input and change events are now triggered.
v4.5.2 is already available on chrome and will be available on firefox and edge in a few days.

Best regards
