### ISSUE TITLE
browser extension is already in version 4.5 but docker containers are still in version 4.4.2

### ISSUE THREAD

**Issue by waliwdenko** [passbolt/passbolt_browser_extension#206]
Passbolt Version: 4.4.2
Platform and Target: Docker
-- Browser: Chrome
-- Web server: Nginx
What you did
We have Passbolt 4.4.2-1 in Docker. Docker repository dont have version 4.5, but Chrome extension is current 4.5.

What happened
Chrome extension in version 4.5 wont work with older (4.4.2) passbolt. When user is logged site is empty (for moment will show screen with "please wait", and after that is only background), when user is logged out and will try recovery access, when he click button from e-mail it works like above (only background shows)

What you expected to happen
Publish docker containers for passbolt 4.5

I reported it also in passbolt/passbolt_docker. I think someone should synchronize publication or provide backward compatibility.

**Comment by cedricalfonsi** [comment]
Hi @waliwdenko,

Along the browser extension update, Chrome was also pushing an upgrade these days.
Did you try to restart your browser?

If the problem persists can you provide the console log of the browser extension. You can obtain them following this steps:
- Go to chrome://extensions/
- Enable "developer mode" in top right
- Click on the index.html under the passbolt tail
- Go to console tab & copy any errors

**Comment by MCH-Chris** [comment]
I am also experiencing the same errors - but have updated the server/api to 4.5.0
When I try to browse to my passbolt instance, the browser console shows 2 of the following errors..

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-[hash-chars...]'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by MCH-Chris** [comment]
FWIW MS Edge Browser v 121.0.2277.106 and Passbolt Extensions 4.4.2 still works

**Comment by waliwdenko** [comment]
I have updated passbolt server/api to 4.5.0 now (docker containers are arrived). But problem still exists - the same as above.
Chrome 121.0.6167.160

**Comment by cedricalfonsi** [comment]
A fix is in the works and will be release later today with v4.5.1.

**Comment by cedricalfonsi** [comment]
Workarounds to this issue are explained in this community post: https://community.passbolt.com/t/cannot-view-passbolt-ce-after-chrome-and-pb-extension-update/9399/5

Thanks for reporting the issue @waliwdenko

**Comment by cedricalfonsi** [comment]
@waliwdenko @MCH-Chris The Chrome extension v4.5.1 was rolled out in production and should solve this issue.
