### ISSUE TITLE
Language UI wrong 

### ISSUE THREAD

**Issue by flexo44** [passbolt/passbolt_browser_extension#207]
## ISSUE NAME
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target:
-- Browser: 121.0.6167.161
-- Web server: nginx 1.15
-- etc.: win 10 22h2

### What you did
I juste lauch my passbolt extension

### What happened
After lauch my google chrome and lauch the passbolt extension the the language of app is wrong.

### What you expected to happen
My system language is french,not english the UI passbolt extension should be fench.

**Comment by Benj1er** [comment]
Hello @flexo44,

Thank you for your report.

Did the issue occur when you created your account?

The language of the passbolt extension must be the one configured in the browser settings.
Could you please check which language is configured in your browser settings?

In any case, you can change the language during setup, recover or in your application profile.

Best regards

**Comment by flexo44** [comment]
Hello Ben,

I apologize for my late reply. My web browser has a good configuration. I don't know the process to change the language during setup, recovery, or in your application profile.

Could you please provide me with the process?

Best regards

**Comment by Benj1er** [comment]
Hello @flexo44,

To change a language during a setup or a recover,  below the card, you can click on the language and update it.
See the images below:
![Setup](https://github.com/passbolt/passbolt_browser_extension/assets/43982352/7719b851-df0c-480c-b44f-c91e00646f4c)
![Recover](https://github.com/passbolt/passbolt_browser_extension/assets/43982352/505a212d-3b29-4ca1-89c7-94e626e89dfb)

In the application, click on your profile in the top right-hand corner:
![Profile](https://github.com/passbolt/passbolt_browser_extension/assets/43982352/3bfd2e26-e4f3-44a7-9d54-330c040e6e42)

When you are in your profile settings, click on the "Edit" button:
![Profile settings](https://github.com/passbolt/passbolt_browser_extension/assets/43982352/affbc4ba-9a82-4a37-9903-171582c5dcdc)

After this process, you can click on the language and update it:
![Edit profile](https://github.com/passbolt/passbolt_browser_extension/assets/43982352/0d2f3e01-cbc0-4569-b020-7cdc716f53b2)

I hope this helps you change the language of the application.
Don't hesitate to come back if it's not clear.

Best regards

**Comment by Benj1er** [comment]
In order to detect the issue, could you give more details ?

What is the passbolt server version ?

Please could you provide a screenshot of the issue (do not forget to hide any sensitive data in the screenshot) ?

Thank you

**Comment by Benj1er** [comment]
Without any feedback, I assume the issue is fixed.
Don't hesitate to reopen it if the issue persists.
