### ISSUE TITLE
Username is put in wrong input field in AWS IAM Sign-in Page

### ISSUE THREAD

**Issue by george-viaud** [passbolt/passbolt_browser_extension#209]
Passbolt Browser Extensions Version: 4.6.0
    Platform and Target:
    -- Browser: Firefox 124.0.1 (64-bit)
    -- Server: All AWS IAM sign-in pages w/ Account ID field - eg: https://test.signin.aws.amazon.com/console/

What you did

1. Browse to https://test.signin.aws.amazon.com/console/
2. Note that the "account" field is correctly set with the account alias "test"
3. Click to insert credentials in passbolt browser extension

What happened
- Username is inserted into field for `account` (over-writing it) instead of `username`. (undesired)
- Password was inserted in the correct field.

Input Fields HTML of login form
```
<input id="account" name="account" type="text" required="" autocapitalize="none" autocorrect="off" value="test" ng-model="vm.account" class="ng-valid ng-not-empty ng-valid-required ng-dirty ng-valid-parse ng-touched">
<input id="username" name="username" type="text" required="" autocapitalize="none" autocorrect="off" value="" ng-model="vm.username" autocomplete="username" class="ng-pristine ng-empty ng-invalid ng-invalid-required psono-findIdentityInputFields-covered ng-touched">
<input id="password" name="password" type="password" required="" autocapitalize="none" autocorrect="off" ng-model="vm.password" autocomplete="current-password" class="ng-pristine ng-empty ng-invalid ng-invalid-required psono-addPasswordFormButtons-covered psono-findIdentityInputFields-covered ng-touched">
```
Observations / possible reason
- Perhaps `account` matches one of the fields detected for username and is chosen as the destination
- If the above is true, it may make sense to change the search order such that `username` and similar precedes `account` so that it prefers `username` and similar as the detected destination
- Alternatively, it may be a good feature to allow the user to specify a target `name`, `id`, `selector` or whatever makes the most sense

This appears to be related to https://github.com/passbolt/passbolt_browser_extension/issues/133

**Comment by Benj1er** [comment]
Hello @george-viaud,

Thanks for your report.
The issue has been fixed in v4.9.0.
v4.9.0 is already available on chrome and will be available on firefox and edge in a few days.
Please feel free to reopen it if the issue persists.

Best regards
