### ISSUE TITLE
Chrome Extension frozen and unusable after some period of inactivity

### ISSUE THREAD

**Issue by doegox** [passbolt/passbolt_browser_extension#211]
## Chrome Extension frozen and unusable after some period of inactivity
* Passbolt Version: Chrome extension v4.7.0
* Platform and Target:
-- Browser: Brave browser 1.65.130
-- Web server: passbolt-ce-server 4.7.0-1 (Debian)
-- etc.: extension v4.6.2 was working fine afaik

### What you did
* Clicking on the icon extension to use it, logging in.
* Not using the laptop for a few hours.
* Coming back, clicking on the icon extension to use it.

### What happened

The icon is red, not gray, because I already logged into the extension some hours earlier.
But clicking on it doesn't do anything, while it should open the extension pop-up.
If I was on a tab for which the extension knows some passwords before letting the laptop unused for a while, the icon still shows the little number. But moving to another tab doesn't refresh or remove that number.
So the extension and its icon appear to be totally frozen, unusable.

### What you expected to happen

I expect the extension to work...

### More info

Going to the extensions list and deactivating/reactivating the extension makes it work fine again (asking me to log in, obviously).

Unfortunately I don't have a recipe to reproduce the error quickly.
It occurred several times but always after some inactivity of several hours.

**Comment by Benj1er** [comment]
Hello @doegox,

Thanks for your report.

Did you manually update the extension from brave://extensions/ in developer mode?
If you reproduce this issue, could you give us more details with the console logs?

A follow-up ticket was created on the internal tracker to reproduce and fix this issue: PB-33410

Best regards

**Comment by doegox** [comment]
Hello 
I'm in developer mode.
I just did update now and got v4.7.7
I restarted the browser and opened the inspection window.
Nothing abnormal now, just the 2 "unauthorized" before I logged in.
I'll let the inspection window open and hope that the issue pops-up after tonight inactivity.

Just before updating to 4.7.7 there was also this error (without waiting hours for a freeze):
```
index.min.js:2 Uncaught (in promise) TypeError: this.cleanAndReload is not a function
    at exec (index.min.js:2:536331)
```

**Comment by doegox** [comment]
So this morning the extension was frozen again.
There were no errors in the console, last errors are some "The tab was closed" from yesterday. 
At this point I cannot even see the source files of the extension, see the "Loading..." at the bottom of the inspection window.
![image](https://github.com/passbolt/passbolt_browser_extension/assets/60773/350f369c-97d0-4754-a7ca-9a8fbe2b37f4)
Here are the last verbose msgs, but I'm not sure if they are from now or yesterday. 
![image](https://github.com/passbolt/passbolt_browser_extension/assets/60773/32d71622-96fc-4e83-928f-5376bc516348)
But I got many similar messages in yesterday activity, so nothing new here I guess.

**Comment by doegox** [comment]
Ha, I found something:
In the network activity I see every minute a `is-authenticated.json?api-version=v2`, until today 02:05 where the connection didn't go through.
![image](https://github.com/passbolt/passbolt_browser_extension/assets/60773/f9301f97-aa3c-48f2-a30b-b018f5269eb4)
while normal connection looks like
![image](https://github.com/passbolt/passbolt_browser_extension/assets/60773/30a647c0-2aed-4cf0-b69a-5f2b94c99871)
And in the "Headers" tab, data is identical to previous connections except that there is no "Remote Address".
It seems either the DNS request didn't happen or didn't get an answer, but when I'm trying to reproduce e.g. with an invalid domain, it stops at "Stalled" and it doesn't go to the "Initial connection" at all in the timing window.

So far I'd say a transient undefined network error in the "is-authenticated" heartbeat caused the extension to hang, but I don't understand why it would cause the inspection window to not even see the source files anymore.

I can try to let a Wireshark running tonight...

**Comment by doegox** [comment]
Digging in the strangeness...
I went to the extension settings, toggled "Allow in Private" to "enable", and the extension started working again.
I thought the extension was simply restarted by the browser as when I deactivate/activate the extension, but toggling again  "Allow in Private" doesn't restart the extension, I'm still logged in. And the Network activity shows requests like `is-authenticated.json` with "Queued at 21.7 hrs" so it seems it's really yesterday extension process which works again.
Maybe more sth related with recent changes in a Brave update rather than changes in Passbolt extension update?

**Comment by Benj1er** [comment]
Thanks for your feedback and the time spent providing information on this issue.
I was able to reproduce it on my side, at first sight the issue occurs only on chromium based browsers when the content of a request is not consumed it remains in progress and after thousands of requests it causes this issue.

This issue should be fixed in the next version, which will be released today or tomorrow.

Thanks again for your feedback, which helped us.

**Comment by Benj1er** [comment]
Hello @doegox,

The v4.7.8 has been published on the chrome webstore.
Let us know if the fix works.

Best regards

**Comment by doegox** [comment]
installed. I'll close the ticket tomorrow if it ran fine > 24h. Thanks!

**Comment by doegox** [comment]
seems fine, thanks again!
