### ISSUE TITLE
Broken group search on password sharing - Groups not showing when there is an uppercase character present

### ISSUE THREAD

**Issue by MaxiStarling56** [passbolt/passbolt_browser_extension#214]
## Broken group search on password sharing
* Passbolt Version: 4.9.0 (docker: `passbolt/passbolt:4.9.0-1-ce-non-root`)
* Platform and Target:
-- Browser: Chrome 126 (also tried with other chrome-based browsers and firefox)
-- Web server: Traefik v3.0.4

### What you did
After updating the browser extension to the latest available in the chrome web store the search function does not work properly anymore.

### What happened
As a user who is part of a group, trying to share a password to the group, i select the password i want to share, then i click on the share button, then searching the group name in full nothing comes up, searching a substring of the group name without the uppercase character i was able to find it. This happens on every group.

Example of the issue:
![issue](https://github.com/user-attachments/assets/99b8b401-2019-46ef-b594-3a5342ddf0c7)

### What you expected to happen
Searching the group full name or a substring the group appears.

**Comment by Benj1er** [comment]
Hello @MaxiStarling56,

Thanks for your report.
A follow-up ticket was created on the internal tracker: PB-34220

Best regards

**Comment by cedricalfonsi** [comment]
This issue was solved with v4.9.1, thank you for your report.
