### ISSUE TITLE
Incorrect table width rendering in Passbolt extension

### ISSUE THREAD

**Issue by aqu1ntero** [passbolt/passbolt_browser_extension#216]
## Incorrect table width rendering in Passbolt extension
* Passbolt Server Version: 4.9.1
* Passbolt Extension Version: 4.9.2
* Platform and Target:
-- Browser: Version 128.0.6613.84 (Official Build) (64-bit)
-- SO: Ubuntu 22.04 and Windows 11
-- Screen resolution: 1920x1080

### What you did
- Open the Passbolt extension and navigate to the password table view.
- Observe the table width and how it renders on the screen.
- Attempt to resize or scroll horizontally through the table.

### What happened
When viewing the password table in the Passbolt extension, the table width is detected incorrectly, resulting in excessively large width values. This issue makes it difficult to navigate the table and prevents proper resizing. The columns appear stretched, and horizontal scrolling is not functioning as expected, which significantly impacts usability.

### What you expected to happen
The table should render with a correct width that fits the content, allowing easy navigation and resizing as needed.

The component calculates the table width incorrectly, resulting in an excessively large value (e.g., 9.64127e+13px). This miscalculation leads to navigation and resizing issues within the table. It seems that when the extension fails to determine the width correctly, it defaults to an unreasonable value.
 
![2024-08-29_11-40](https://github.com/user-attachments/assets/5f42f94b-0c46-4667-be93-f242a32f1671)

**Comment by Benj1er** [comment]
Hello @aqu1ntero,

Thanks for your report.

This issue has now been corrected.
Once you have updated the width of each column to a default value (hide and show the column to set the default value), this should no longer occur.

If the issue persist, don't hesitate to reopen the ticket.

Best regards.
