### ISSUE TITLE
[PB-36501] Share Dialog Suggestions Ordering

### ISSUE THREAD

**Issue by Tenac451** [passbolt/passbolt_browser_extension#217]
## Share Dialog Suggestions Ordering
* Passbolt Version: 4.9.1-1-pro
* Platform and Target:
-- Browser: Chrome 128.0.6613.113 (Offizieller Build) (arm64) 

### What you did
I have tried to share a resource with a group. 

### What happened
We have many groups with the format “section-\*”.
But we also have a group called “section” when I search for “section” in the sharing dialog I only get 10 results which only contain “section-\*”. So I have no possibility to select the group “section”. 
As a workaround I have to use the CLI tool or the Android app.

### What you expected to happen
When I search for “section” the top entry should be “section” followed by “section-\*” entries. Since “section” cannot be more specific.

**Comment by cedricalfonsi** [comment]
Thank you for your report.

We’ll investigate the impact of either removing or increasing the current limit. If you’d like to provide more details, could you share the number of groups you have under management that start with "section"? This will help us in the analysis.

In the long term, we're considering introducing pagination for the search as a more scalable solution.

**Comment by cedricalfonsi** [comment]
Internal ticket reference: PB-36501
