### ISSUE TITLE
Can't connect to passbolt using firefox 131.0.2 on ubuntu 24.04

### ISSUE THREAD

**Issue by haubourg** [passbolt/passbolt_browser_extension#219]
Hi, 
paid user with a company account here. 
Trying to connect as usual, I get (in french) 

`Impossible de vérifier la clé du serveur. x-gpgauth-authenticated should be set to false during the verify stage`

* Passbolt Version: current saas deployed at https://cloud.passbolt.com/
* Platform and Target:
-- Browser: Firefox 131.0.2 via apt ppa https://packages.mozilla.org/apt (no snap  sandboxing)
-- Ubuntu 24.04. all pacakges updated to the latest version

I have firefox extension multicontainer installed but I a not in a container tab, nor in a private window. 

Chromium works fine on the same OS. 

possibly related to https://github.com/passbolt/passbolt_api/issues/404 

any idea?

**Comment by qntoni** [comment]
Hello @haubourg,

We've seen similar issues recently, it looks like clearing the cookies may help here. 

Please, could you try clearing the cookies and see if it resolves the issues?

Thanks in advance.

Best regards,
Antony

**Comment by haubourg** [comment]
Thanks for the fast answer. I did clear the cookies and succeeded to log in. 
Thanks a lot!

**Comment by qntoni** [comment]
Thanks for letting us know!

In that case, I'll close this issues. In the future, if you run into any other issues or if you have any technical questions, I recommend using [PRO support](https://passbolt.com/contact/support).

Wish you a great day!

Best regards,
Antony
