### ISSUE TITLE
Memory leak on password creation

### ISSUE THREAD

**Issue by Ducatel** [passbolt/passbolt_browser_extension#22]
Hi Passbolt team,

One Chrome (linux and windows) with extension `1.4.0` and `1.5.0-RC1`
There is an explosion of memory consumption after each new password entry created.

* Just connected to Passbolt: 210Mo
* Add a password entry: 260Mo
* Add a new one: 310Mo
* Again: 357Mo
* And continue to grow again and again

**Comment by stripthis** [comment]
Fixed with 1.5.1.
