### ISSUE TITLE
Cannot read/save 'some' TOTP  - Multipart QR codes are not supported

### ISSUE THREAD

**Issue by Si-Richards** [passbolt/passbolt_browser_extension#221]
## ISSUE NAME
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target:
Passbolt 4.9.1 - RPM
PHP version 8.2.23
Rocky Linux

### What you did
Some not all QR codes cannot be read into Passbolt via web or mobile

### What happened
Some QR codes receive error 'The QR code is incomplete' but they can be read into both Google or MS Authenticator apps

### What you expected to happen
The QR should be decoded and saved against the Passbolt record

![image](https://github.com/user-attachments/assets/40626bd6-8a44-4c7f-8de5-702cf064c683)

**Comment by stripthis** [comment]
Can you post an example of QR code that doesn't work?

**Comment by Si-Richards** [comment]
Thanks guys....

To be clearer... Passbolt seems unable to parse Multiformat QR codes which seem to be becoming more common.
If strip out the extra it reads fine

**Comment by cedricalfonsi** [comment]
We are curious about the kind of data represented in the QR code, given that the amount of data required to represent a TOTP is typically small. Could you please share with us the software that is producing this information? We'd be happy to investigate further.

**Comment by cedricalfonsi** [comment]
Closed due to inactivity.
