### ISSUE TITLE
Multiprocess (e10s) support in Firefox

### ISSUE THREAD

**Issue by MegaphoneJon** [passbolt/passbolt_browser_extension#23]
Firefox is reporting the browser extension as not being Electrolysis-compatible.  Since I've only used Passbolt for a few minutes I can't adequately say if there's missing functionality - you may just be able to mark the extension as e10s-compatible and reupload to addons.mozilla.org.

**Comment by stripthis** [comment]
Hello, 

To my knowledge v1.5.0 and bellow are not compatible because we use some of the old SDK components. This should be fixed with version v1.6.0 where we will switch to firefox webextension.

Cheers,

**Comment by chemnic** [comment]
I have this problem in version 1.6.2.

**Comment by stripthis** [comment]
This is fixed.
