### ISSUE TITLE
Firefox warns "this connection is insecure" in the extension iframe

### ISSUE THREAD

**Issue by ktosiek** [passbolt/passbolt_browser_extension#24]
I'm getting the warning about entering password on insecure page when working with the plugin's iframe. I'm serving passbolt over HTTPS. This is with version 1.4.0 of plugin and server.

**Comment by stripthis** [comment]
We believe this is a bug with Firefox. You see the related issue there: https://bugzilla.mozilla.org/show_bug.cgi?id=1367064

**Comment by stripthis** [comment]
<img width="1277" alt="screen shot 2017-05-18 at 19 35 59" src="https://cloud.githubusercontent.com/assets/77410/26359087/224afe42-3ff2-11e7-9d22-1eb8851c758e.png">
![screen shot 2017-05-18 at 19 36 15](https://cloud.githubusercontent.com/assets/77410/26359086/2227b176-3ff2-11e7-9cb3-b2940518f5a7.png)

**Comment by stripthis** [comment]
This issue is fixed with version v1.6.2.
