### ISSUE TITLE
I can't share passwords in chrome 59.0.3071.86 on macOS Sierra 10.12.5

### ISSUE THREAD

**Issue by pablodgonzalez** [passbolt/passbolt_browser_extension#27]
The password creation works good, but when I want share the password the waiting screen freezes and stops responding

**Comment by stripthis** [comment]
Hello @pablodgonzalez, are you using v1.5.1 for both the server and the extension?

**Comment by pablodgonzalez** [comment]
@stripthis efectly the server wasn't in the same version. I've not checked that. For some reason my extension was updated without message (at least I haven't seen it).
Now we are running server and extension over 1.5.1 version without problems.
Thanks!
