### ISSUE TITLE
As a user using the Vivaldi browser, the login page should not show firefox logo

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_browser_extension#29]
Using the Vivaldi browser with the chrome plugin seems to work, but the firefox plugin is offered instead.

Not sure if you need to test but on the surface it appears to work fine.

**Comment by stripthis** [comment]
Thank you for your feedback. Please note that vivaldi browser is currently not officially supported (even if it works).

**Comment by mannp** [comment]
Understood thanks.

**Comment by stripthis** [comment]
Moved to : https://community.passbolt.com/t/as-a-user-i-can-use-with-passbolt-with-vivaldi-browser/78
