### ISSUE TITLE
FF50/1.2.0/Win7: nothing happens when clicking on the "download" key button during setup and on profile / manage key

### ISSUE THREAD

**Issue by ipshenicyn** [passbolt/passbolt_browser_extension#3]
Just not happens anything.
"console" and "network" is empty. 

screenshot: https://drive.google.com/file/d/0B2IQYa2K6pa0bW5TYWk0WWs0VzA/view?usp=drivesdk

**Comment by stripthis** [comment]
Hello,

I just double checked with Firefox 50.0.2 and 51.0a2 but I could not reproduce the issue.
Can you tell me which operating system you are using, which version of firefox and passbolt plugin you are using?

Please also check in the browser console (Ctrl + Shift + J) to see if there is any error from the extension listed there (errors won't be in the default web console). See. https://developer.mozilla.org/en/docs/Tools/Browser_Console

Cheers,

**Comment by ipshenicyn** [comment]
windows 7
FF 50.0.2 (just updated from 49.0)
plugin 1.2.0

How about this button? https://goo.gl/JrmJID
Do it works for you? For me - not working too. 
If this button is the same function, as in topic start - perfect, because I don't want reset my key again)

The browser console: https://goo.gl/h8NjsY

**Comment by stripthis** [comment]
Hi,

I just tested under linux and macos and could not reproduce the issue. I'll see if I can get my hand on a windows 7 setup, but that might take a while. The download button in the profile page is not exactly the same, but it seems to be the same issue in your case, so no need to create a new topic.

The console screenshot looks like the web console and not the browser console. The web console (Ctrl + Alt + K) displays the error from the passbolt.js app, and the browser console(Ctrl + Shift + J)  displays the error from the plugin. Can you send both?

![screen shot 2016-12-07 at 16 05 36](https://cloud.githubusercontent.com/assets/77410/20964324/127c1232-bc97-11e6-9450-cdc1dffe9419.png)

**Comment by stripthis** [comment]
Hi @ipshenicyn 

We just tested under Windows 7 and it works. Maybe there is something wrong an antivirus or another "security" plugin preventing the download?
 
<img width="1412" alt="capture du2019u00e9cran 2016-12-07 u00e0 12 13 45" src="https://cloud.githubusercontent.com/assets/77410/20965655/c1a91034-bc9c-11e6-9ce7-e5115ef6c69f.png">

**Comment by ipshenicyn** [comment]
No, it's exactly "browser console" (ctrl+shift+j): https://goo.gl/PDW50i
Screenshot from the setup process: https://goo.gl/8MNWRC

But, now I'm can't to return in the my last account, because I haven't downloaded secret key) It's not big deal, because that account was empty.

**Comment by ipshenicyn** [comment]
Full reinstall FF without any extension resolved the problem. Unfortunately, I don't figured out in what exactly was the problem. I tried turn off all extension (before reinstall browser), but it no had any effects.

Any way, thank you for so fast answers! I'm sorry for wasting your time.
