### ISSUE TITLE
As a user I can configure passbolt browser extension to work with multiple passbolt instances

### ISSUE THREAD

**Issue by patrickhanft** [passbolt/passbolt_browser_extension#31]
We use passbolt for a hobby project, where I work with a team of several technical people. 

The concept is so convincing, that passbolt now becomes very interesting for me also to be used in my professional background with other teams, which means, I would be using different instances of passbolt. But for now, as far as I understand, the browser extension can only be used with one instance of passbolt.

My workaround to separate hobby and professional stuff is to use different browser identities within chrome. For this usecase it is very reasonable, but I don't want to create several professional browser identities just for different professional projects with different teams, because there are multiple passbolt instances involved. 

So it would be great, if the passbolt browser extension supported more than a single passbolt setup.

**Comment by stripthis** [comment]
Thank you for the suggestion @patrickhanft, it's been in our mind as well. We'll come to this at some point, though most likely not this year.

**Comment by elboletaire** [comment]
I'd like to see this feature too

**Comment by gtrias** [comment]
I would need this feature as well.  :) 

I have a personal passbolt installation and other for our company credentials and we have to recover account any time we switch between instances

**Comment by elboletaire** [comment]
> I would need this feature as well. :)
> I have a personal passbolt installation and other for our company credentials and we have to recover account any time we switch between instances

Same issue here

**Comment by stripthis** [comment]
@elboletaire @gtrias the best workaround right now is to switch between browser profiles. 

Moved to: https://community.passbolt.com/t/as-a-user-i-can-configure-passbolt-browser-extension-to-work-with-multiple-passbolt-instances/77

**Comment by mariomelofilho** [comment]
bump!

**Comment by Sphiinx** [comment]
I'm surprised that this is not already a feature.

**Comment by Dual-Boot** [comment]
Hello

This feature is a real need.
 Is there anything planned ?

 Regards,

**Comment by belorenz** [comment]
This would be great!

**Comment by VetheonGames** [comment]
This feature would be amazing
