### ISSUE TITLE
Extension cannot be installed under Firefox 57.0b1 (developer edition)

### ISSUE THREAD

**Issue by elboletaire** [passbolt/passbolt_browser_extension#33]
Firefox is changing how extensions are managed and, apparently, they changed something in how the `install.rdf` file is interpreted, because it ignores the `em:maxVersion` setting as  `*`.

![imatge](https://user-images.githubusercontent.com/153305/30691808-3f778ed2-9ec9-11e7-8202-f08e23dd7641.png)

You can download firefox developer edition from https://www.mozilla.org/en-US/firefox/developer/

**Comment by stripthis** [comment]
Yes firefox 57 drops the support for legacy extension. The next release will fix that, we're still waiting for 100 users to update to 1.6.5 (required to migrate the storage). We'll try to publish 1.6.6 on firefox dev chanels soon (this week or early next week).

**Comment by elboletaire** [comment]
Ok thanks!

**Comment by reeslo** [comment]
👍

**Comment by stripthis** [comment]
v1.6.6 fix this issue. Enjoy!

**Comment by elboletaire** [comment]
Perfect thanks! 😄
