### ISSUE TITLE
Where is plugin data stored?

### ISSUE THREAD

**Issue by lanaiscool** [passbolt/passbolt_browser_extension#34]
I reinstalled a passbolt instance however the problem now occured since there is no option to reset the extension im unable to login removing the extension than removing the cache and even removing extension data in about:config doesnt do anything os i would like to know where the data is stored so l can delete it and login to my passbolt instance

**Comment by cedricalfonsi** [comment]
Hello @lanaiscool,
By following the registration link you received from your new passbolt instance (after creating a new account) it will override your existing settings with the new one.

**Comment by lanaiscool** [comment]
is there any other way then deleting my user and readding it since the registration link is already used and not valid anymore also going to /recovery wont work

**Comment by stripthis** [comment]
@lanaiscool you can log in mysql database and delete the user manually.

**Comment by stripthis** [comment]
Ref. https://github.com/passbolt/passbolt_api/issues/73

**Comment by lanaiscool** [comment]
okay i will try it but still is there a way to reset the extension by deleting data i mean it is stored somewhere right ?

**Comment by stripthis** [comment]
The data is stored in chrome.storage, i'm unsure what is the procedure to remove the data outside doing programmatically in the extension. As cedric said if you register with new user (e.g. after deleting the old one) data will be replaced.

https://developer.chrome.com/extensions/storage

**Comment by lanaiscool** [comment]
for everyone facing the same issues as me the extension data is stored in /home/user/.mozilla/firefox/profile.default/browser-extension-data/ if you delete the passbolt folder and restart firefox the extension has been reset 
For chrome/chromium
you can just remove the extension and reinstall it to work

**Comment by stripthis** [comment]
@lanaiscool thanks for the info, we'll add it to the documentation.

**Comment by jpoorni** [comment]
> @lanaiscool you can log in mysql database and delete the user manually.

Hi, which tables ? i deleted all users.. but still the same issues. Think browser is storing the data somewhere. i reinstalled the chrome and installed too...

**Comment by jpoorni** [comment]
Hi, i am facing the same issue. need to change the server in the passbolt_extension. how to do it

**Comment by garrettboone** [comment]
> Hi, i am facing the same issue. need to change the server in the passbolt_extension. how to do it

The normal step is to uninstall the browser extension, and then reinstalling the extension from the browser extension store like the first time you installed it (after visiting your passbolt login page). More help is offered in the forum.
