### ISSUE TITLE
Changing tab while logging in redirects the wrong tab to passbolt

### ISSUE THREAD

**Issue by ktosiek** [passbolt/passbolt_browser_extension#35]
Passbolt version: 1.6.5 (plugin and server)
Browser: Firefox 57.0b8

Steps to reproduce:
* open the login page
* type in the password, press login
* change tab *before the page reloads*

Actual behaviour: the tab I'm on is redirected to Passbolt, the tab I've used for logging in shows a spinning gear.
Expected behaviour: only the tab I used to log in should be affected.

**Comment by stripthis** [comment]
Fixed with 2.0.5
