### ISSUE TITLE
Typo in setup step title ("them numbers")

### ISSUE THREAD

**Issue by palant** [passbolt/passbolt_browser_extension#36]
The string defined [here](https://github.com/passbolt/passbolt_browser_extension/blob/91e30c2e2df9c699018c3be1f01b9b5761bffc22/src/all/data/js/setup/workflow/installSetup.workflow.js#L39) currently says:

> Give us a second while we crunch **them** numbers!

I assume that it should have been:

> Give us a second while we crunch **the** numbers!

**Comment by stripthis** [comment]
It's actually done intentionally to give the interface language some character. It's an old regional English pattern. https://www.quora.com/Why-do-people-use-them-instead-of-those

We can change that though, if more people find it confusing

**Comment by palant** [comment]
Fine with me if it is intentional.
