### ISSUE TITLE
Firefox plugin claiming to be Chrome

### ISSUE THREAD

**Issue by OdyX** [passbolt/passbolt_browser_extension#39]
With multiple passbolt instances (and one browser per instance); I often get https://github.com/passbolt/passbolt_browser_extension/blob/042b07d14fa70deb6f8dd3a00e6393ef6cb8a384/src/all/data/ejs/login/wrongDomain.ejs#L22
… on Firefox.

**Comment by stripthis** [comment]
Fixed with 1.6.9
