### ISSUE TITLE
As LU creating/editing a password I cannot see the last characters of my long secret

### ISSUE THREAD

**Issue by cedricalfonsi** [passbolt/passbolt_browser_extension#40]
## Long secret hidden
* Passbolt Version: 1.6.9
* Platform and Target: *

### Reference
PASSBOLT-2742

### What you did
1. Create a password
2. Add a long secret, by instance : abcdefghijqlmnopqrstuvwxyz

### What happened
Last characters of the secret are hidden behind the security token.

![image](https://user-images.githubusercontent.com/1582917/36972621-cee1e0ce-2095-11e8-82f1-fc95720a1835.png)

### What you expected to happen
I should be able to see the hidden characters

**Comment by stripthis** [comment]
Fixed with v2.1
