### ISSUE TITLE
Can't login with Chrome Plugin

### ISSUE THREAD

**Issue by DanielBoettner** [passbolt/passbolt_browser_extension#42]
## Can't login with Chrome Plugin
* Passbolt Version: 1.6.9
* Platform and Target:
  *  Browser: Chrome Version 65.0.3325.162 (Official Build) (64-Bit)
  * Web server: Nginx/1.12.2
  * etc.: Passbolt running on passbolt **docker** image
  * the docker server is not publicly reachable (IP restrictions)
  * A backup of the original code deployed with the docker image was made, than a git clone for current master branch was made. (the below error, was appearing before and after that)

### What you did
Visited the URL for our Passbolt docker instance. The instance requiring a custom port (4242).
No matter if new account ist registered or an existing account is retrieved, the user setup runs well.

### What happened
While login with Firefox works fine, the login in Chrome has no success. At the very end when going to the URL again, in Chrome the login wont work though.

### What you expected to happen
Login into Passbolt succeeds.

# Further information
### Core
* Debug mode is on
* Could not reach the /healthcheck/status with the url specified in App.fullBaseUrl
### Application configuration
* This installation is not up to date. Currently using 1.6.9 and it should be v2.0.0-rc2.

## More
For a colleague it works, will try to determine if there is a incompatibility with other plugins.

**Comment by cedricalfonsi** [comment]
Hello @DanielBoettner,

Do you have any new information regarding the bug you encountered ?
