### ISSUE TITLE
Firefox plugin prevents display of XML pages

### ISSUE THREAD

**Issue by colinfrei** [passbolt/passbolt_browser_extension#45]
## ISSUE NAME
Passbolt extension 1.6.10, Passbolt version 2.0.1
* Platform and Target:
-- Browser: Firefox (Developer Edition) 60.0b10 on OSX

### What you did
Go to a website that outputs XML, with a Content-Type header of application/xml
I expect the browser to show me the XML, something like this:
<img width="432" alt="screen shot 2018-04-20 at 09 56 35" src="https://user-images.githubusercontent.com/752836/39037589-3804ab7c-4481-11e8-8224-991a68d04bc8.png">

### What happened
The XML displays for just a flash, then only a white page is shown. The XML is still there (I see it in view source or the network tab), it's just not being displayed.

### What you expected to happen
XML should be displayed normally.
When I disable the Passbolt plugin it does so again.

**Comment by SergiuEnachi** [comment]
> XML should be displayed normally.
> When I disable the Passbolt plugin it does so again.

This is still actual with FF Quantum 64.0 (64-bit) running on Windows 10 (64bit) and  Passbolt plugin version 2.4.6. 
and getting annoying to play with enabling/disabling the plugin just to have xml parsed correctly

**Comment by stripthis** [comment]
@SergiuEnachi I'll have a look shortly

**Comment by rgpublic** [comment]
Ah finally I found the culprit and this bug. I always wondered why my XML broke :-( This still happens in 2020. Any progress on this issue?

**Comment by rgpublic** [comment]
FWIW there seem to be numerous other extensions that also suffer from this bug:
https://stackoverflow.com/questions/10649253/why-xml-file-is-not-rendered-properly-in-firefox

**Comment by stripthis** [comment]
@rgpublic the last time I checked I couldn't find what was causing the issue. While I can reproduce the issue, I didn't manage to identify the root cause. Initially I thought maybe passbolt was modifying the page, but that's not the case.

**Comment by rgpublic** [comment]
@stripthis Very mysterious. I also found this bug here, but it's supposed to be resolved:

https://bugzilla.mozilla.org/show_bug.cgi?id=1605657

Nevertheless, it happens for me. Even stranger is the fact that it doesn't happen on my machine at home, but it happens 100% reproducible on my machine here at the office. Both have the same OS, the same Firefox version, both have the Passbolt plugin installed. I'm stumped.

**Comment by rgpublic** [comment]
Quick tip for anyone still suffering from this: You can just add "?magic=wow" or sth. (any query string will do) to the URL to resolve this. Probably better than disabling Passbolt all the time ;-)

**Comment by aTanCS** [comment]
I can confirm the issue with Firefox 89.0.2 and Passbolt Extension 3.2.3. Disabling the extension fixes XML view.

**Comment by garrettboone** [comment]
Also from https://stackoverflow.com/questions/10649253/why-xml-file-is-not-rendered-properly-in-firefox `CTRL-U` opens as `view-source:https://www.w3schools.com/xml/note.xml` which renders fine:
![image](https://user-images.githubusercontent.com/47018474/125011055-ba64f880-e035-11eb-8e8a-a91749deb832.png)

**Comment by cedricalfonsi** [comment]
Seems to have been fixed. Don't hesitate to reopen if the problem occurs again.
