### ISSUE TITLE
security token check by registration does not work.

### ISSUE THREAD

**Issue by yoshito-maeoka** [passbolt/passbolt_browser_extension#46]
## security-token by registration is not checked if it has 3 characters.
* Passbolt Extention Version: 2.0.10
* Platform and Target:
-- Browser: Firefox 2.0.10 / Chrome 2.0.10
-- Web server: own hosting / 2.0.7
-- etc.: 

### What you did
an User configured her / his account with 2 charactes security token, but without error-check it went until end.

### What happened
 and got infinity-loop. Only Chrome shows error message on the viewport, but no detail has been displayed. I found error message in Developer Tool 'securityToken: "A token code cannot be empt' or like that.

### What you expected to happen
on the screen 'We need a visual cue to protect us from the bad guys' should be checked if the security token should be 3 Characters. and never go to end until 3 characters are filled

**Comment by stripthis** [comment]
Thanks for the report @yoshito-maeoka i'll have a look

**Comment by stripthis** [comment]
Fixed with v2.1
