### ISSUE TITLE
Chrome extension don't do anything (not recognized)

### ISSUE THREAD

**Issue by winkelement** [passbolt/passbolt_browser_extension#47]
## Chrome extension don't do anything (not recognized)
* Passbolt Version: 2.1.0 CE
* Passbolt Extension Version: 2.2.1 
* Platform and Target:
-- Browser: Chrome 68.0.3440.106
-- Web server: Official Passbolt Docker Image
-- etc.: OS X 10.11.6

### What you did
Installed the Passbolt Docker Image, everything works fine. Tested it at Computer (A) with OS X and latest Chrome, the "home" page points me to download the Chrome extension, which works fine. After that i can use Passbolt on Computer (A). Trying to do the same on another Computer (B) don't work. 

### What happened
After installing the Chrome extension on Computer (B), it shows up in "extensions" and is enabled. Also the icon shows up in the menu bar. Reloading the passbolt "home" page tells me again to install the extension. Klicking on the extension icon did nothing at all. Restarting Chrome and Computer (B) did not help.

### What you expected to happen
Chrome extension working on Computer (B) like it does on Computer (A).

**Comment by cedricalfonsi** [comment]
Hello @winkelement,
Do you still experience this issue with the latest version?

**Comment by winkelement** [comment]
Yes i'm having the exact same error with a 2.5.0/2.4.4 combination. The user account where i have problems uses a network home folder (afpfs). Also the Firefox Plugin works fine on the same account.

**Comment by stripthis** [comment]
Closing as stale. Feel free to reopen if you encounter this, with ideally some information to reproduce the issue.
