### ISSUE TITLE
Passbolt Share Secrets and Edit Groups Issues after Update Extension to 2.4.1

### ISSUE THREAD

**Issue by leomazzo** [passbolt/passbolt_browser_extension#48]
## Extension 2.4.1
* Passbolt Version: 1.6.0
* Platform and Target:
-- Browser: Chrome Version 69.0.3497.100 - 64bits
-- Web server: Apache 2.4 / PHP 7
-- etc.: Ubuntu 16.04

### What you did
After downgrade the version of the addon on Firefox or install the old version of extension on Chrome, the Passbolt functionalities stayed normal again. 

### What happened
In October, 15, 2018, Google Chrome updated the Passbolt extension to version 2.4.1. After that we cannot Share the secrets or edit groups. While we are trying to use these functionalities, the browser freezes and not complete the operation. We have more than  40 users in the same situation. In the Firefox, with the addon on the version 2.4.1 the same problem is occurring.

### What you expected to happen
In Google Chrome we have no option to avoid the automatic update of the extensions. We are using Firefox and installing the old version of extension (any older than 2.4.1) .
We would expected that the updated of the extension not affected our production systems.

**Comment by cedricalfonsi** [comment]
Hello @leomazzo,

I'm sorry to hear that your passbolt is not working properly anymore.

Passbolt version 1 is deprecated since june 2018, you should upgrade to version 2.
You'll find instructions here: https://help.passbolt.com/hosting/upgrade

**Comment by cedricalfonsi** [comment]
I cannot reproduce it with passbolt API v2.1.0 and chrome 69
