### ISSUE TITLE
Error: The secret cannot be decrypted when click on cancel in password modal

### ISSUE THREAD

**Issue by 1Jesper1** [passbolt/passbolt_browser_extension#49]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to an installation: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt Browser Extensions.
For passbolt API, docker, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new Browser Extension bug please use the following format:

## ISSUE NAME
* Passbolt Version: 2.4.0
* Platform and Target:
-- Browser: Chrome

### What you did
Cllick on cancel or close icon in get password modal.

### What happened
The error: "Error: The secret cannot be decrypted" shows.

### What you expected to happen
No error should be showed.

**Comment by cedricalfonsi** [comment]
Thank you for your report @1Jesper1

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.0
