### ISSUE TITLE
Firefox extension trigger master password request on start

### ISSUE THREAD

**Issue by LeBenLeBen** [passbolt/passbolt_browser_extension#51]
## Firefox extension trigger master password request on start
* Passbolt Version: 2.4.2
* Platform and Target:
-- Browser: Firefox 63.0
-- Web server: I don't know

### What you did
* Install the Passbolt extension for Firefox
* Start Firefox without any additional action

### What happened
* A prompt for the Firefox master password is shown without any explanation

### What you expected to happen
* No random, unexplained prompt should show up on start
* I don't understand why Passbolt requires my master password and this should be better explained
* The password prompt should be asked when I interact with Passbolt extension and not before that

**Comment by stripthis** [comment]
Hi @LeBenLeBen,

Can you explain what you mean by "on start".
Passbolt never ask master passwords unless you perform an action so that seems strange.

**Comment by LeBenLeBen** [comment]
When I start Firefox. I disabled Passbolt extension to be sure it was the cause and the prompt disappeared.

![capture d ecran 2018-10-29 a 16 54 25](https://user-images.githubusercontent.com/793344/47663292-f1a05d80-db9c-11e8-8461-dde3ae561477.png)

**Comment by LeBenLeBen** [comment]
After playing a bit with it, I'm wondering if that could be caused by our vault server being protected behind a basic auth for which I have stored the credentials in the Firefox password manager which itself requires the master password to be unlocked.

I'll investigate further and report back.

**Comment by stripthis** [comment]
@LeBenLeBen I tried locally and couldn't reproduce. Maybe you used firefox "remember" functionality for some forms within passbolt that is triggering the behavior. Thanks for investigating further.

**Comment by LeBenLeBen** [comment]
Ok we definitely have a permanent HTTP basic auth on the vault server and this is partially the cause of the issue. Removing the basic auth credentials I saved in Firefox removes the master password prompt on start. I guess I'll deal with it and login twice to access the passwords the few times I need to 😅
