### ISSUE TITLE
TypeError: aro is undefined in shareChanges.js

### ISSUE THREAD

**Issue by janoskaz** [passbolt/passbolt_browser_extension#55]
## TypeError: aro is undefined in shareChanges.js
* Passbolt Version: 1.6.9/2.4.4
* Platform and Target:
-- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
-- Web server: Apache/2.4.6 (CentOS) 

### What I did
- I check record in list of all items
- I click share
- Passbolt freezes

### What happened
- Passbolt becomes unresponsive
In the console, I see following error:
`uncaught exception: [object Object]
TypeError: aro is undefined[Zjistit více] shareChanges.js:30:13 `

### What I expected to happen
- Dialog for sharing password should appear

**Comment by stripthis** [comment]
thanks for the report @janoskaz we'll look into it.

**Comment by cedricalfonsi** [comment]
@janoskaz Passbolt version 1 is deprecated since june 2018, you should upgrade to version 2.
You'll find instructions here: https://help.passbolt.com/hosting/upgrade
If you encounter any issue checkout the community [forum](https://community.passbolt.com).
Cheers

**Comment by janoskaz** [comment]
@cedricalfonsi Thanks for sorting this out
