### ISSUE TITLE
login broken on chromium 71

### ISSUE THREAD

**Issue by wommel** [passbolt/passbolt_browser_extension#56]
## login broken on chromium 71
* Passbolt Version: 2.5.0
* Platform and Target:
-- Browser: Chromium 71.0.3578.80 Arch Linux
-- Web server: nginx/1.15.6
-- etc.: plugin version 2.4.5

### What you did
enter password on login page, click login button.

### What happened
reload of login page

### What you expected to happen
show passwordlist

**Comment by wommel** [comment]
works in chromium 70 and firefox

appears in new as well as existing profiles

**Comment by wommel** [comment]
sry seems to be related to administrative device policy to block third party cookies 

thanks for the quick response thou

**Comment by stripthis** [comment]
Hello @Melkor333 if the login page seems to work and then the user is reverted back to the login page, most likely there is an issue with the way cookies or sessions are managed. Maybe worth trying is clearing the cookies cache to see if it could be an old cookie (from v1?) that is not valid and not being reset.

If that does not work you double check what configuration they have in chrome://settings/content/cookies
<img width="861" alt="screenshot 2018-12-11 at 09 33 47" src="https://user-images.githubusercontent.com/77410/49787817-ef96f600-fd27-11e8-9581-2bd3bfd6379b.png">

 Also can you check if the have other plugins installed that could conflict with passbolt? Can you tell me also which operating system they use?

**Comment by stripthis** [comment]
No problem @Melkor333, i'm glad it helped.
