### ISSUE TITLE
Improvement: use consistent wording

### ISSUE THREAD

**Issue by joachimneumann** [passbolt/passbolt_browser_extension#58]
Users might be confused about the wording in the GUI.

Password / Passphrase
================
In the Login page, the Passbolt Passphrase is referred in three different ways: as "Master Password" and "secret key passphrase"  and "passphrase".

When a new user is logging in the first time, he is asked to "Set your passphrase" in a field with the placeholder "enter your password here".

<img width="758" alt="Screenshot 2019-03-10 at 07 25 46" src="https://user-images.githubusercontent.com/5642225/54081483-c295b780-4305-11e9-9590-3afbe93b8ec7.png">

<img width="506" alt="Screenshot 2019-03-10 at 05 36 27" src="https://user-images.githubusercontent.com/5642225/54081470-aabe3380-4305-11e9-875b-095a1b695e8a.png">

I would propose to consistently use Passphrase and use the term password only for the passwords stored in Passbolt.

Username
=======
The username is not clearly stated in the welcome email: In this screenshot of the welcome email, which is my username, "joachim", "joachim@mindo.io" or something else?

<img width="498" alt="Screenshot 2019-03-10 at 05 30 31" src="https://user-images.githubusercontent.com/5642225/54081497-fb359100-4305-11e9-95a8-0ff9417b662f.png">

**Comment by abhinavkumar940** [comment]
Thank you @joachimneumann for reporting this issue.

I am happy to inform you that this has been taken care of and will likely be part of our next release.

**Comment by abhinavkumar940** [comment]
Fixed with v2.8.3
