### ISSUE TITLE
Clean Login page

### ISSUE THREAD

**Issue by joachimneumann** [passbolt/passbolt_browser_extension#59]
(This is of course a matter of personal taste)

I would like to propose a simplified login **after** the plugin has been installed.

The messages "Nice one! The plugin is installed and configured. You are good to go!" and "The server key is verified. The server can use it to sign and decrypt content." are not really needed and can confuse technically less literate users.
If the Server could not be verified, the username and passphrase fields should probably not be shown at all and a big warning should be displayed.

My proposal for the login screen would be:

<img width="1099" alt="Screenshot 2019-03-11 at 09 20 34" src="https://user-images.githubusercontent.com/5642225/54109655-8afb3e00-43df-11e9-865c-9230eea1a3f8.png">

**Comment by stripthis** [comment]
Yes we already have a prototype for a simplified setup and login in the styleguide. Please post feature request ehancement on the forums, as indicated in the issue template.

<img width="692" alt="Screenshot 2019-03-11 at 09 39 33" src="https://user-images.githubusercontent.com/77410/54110405-98b1c300-43e1-11e9-8544-3cc0a96a6bed.png">
mplate, we only use github for bugs.
