### ISSUE TITLE
dist/all directory not found (Error in readme)

### ISSUE THREAD

**Issue by rnsw** [passbolt/passbolt_browser_extension#60]
I follow this process.

git clone https://github.com/passbolt/passbolt_browser_extension.git
cd passbolt_browser_extension
npm install
sudo npm install web-ext -g
sudo npm install crx -g
grunt
grunt watch
cd dist/all        **here not found**

**Comment by stripthis** [comment]
There is a mistake in the doc it should be `build/all` not `dist/all`

**Comment by rnsw** [comment]
thanks

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.2
