### ISSUE TITLE
Autofill on hub.docker.com doesn't work

### ISSUE THREAD

**Issue by sdillen** [passbolt/passbolt_browser_extension#61]
## Autofill on hub.docker.com doesn't work
Passbolt Version: 2.8.3
Passbolt Extension Version: 2.8.2
Target: https://hub.docker.com
Browser: Google Chrome

### What you did
I tried to login via the Passbolt Browser Extension and the autofill failed.

**Comment by stripthis** [comment]
@sdillen thanks for the report. The functionality is new, so some issues were expected. Thanks for the report it's very useful.

**Comment by cedricalfonsi** [comment]
Fixed with v2.11.0
