### ISSUE TITLE
Sorted users only shows the top 50 entries

### ISSUE THREAD

**Issue by MMeent** [passbolt/passbolt_browser_extension#62]
## Users sorted (on last seen) only shows the first few entries, and does not load more entries.
* Passbolt Version: 2.8.3 / 2.8.2
* Platform and Target:
-- Browser: FF 67.0b4 
-- Web server: Passbolt Docker edition

### What you did
- In the general users view
- ... with > 60 non-deleted users
- ... as an admin
- ... I sorted the users on 'last seen'
- ... and scrolled to the bottom

### What happened
The list only shows ~50 (guess, not counted) entries, not including the (users last/never seen, depending on sorting direction)

### What you expected to happen
The list should load more users, sorted by last seen, continuing on from where the other started.

**Comment by stripthis** [comment]
@MMeent thank you for the bug report. @cedricalfonsi is looking into it.

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.3
