### ISSUE TITLE
Password generator cycle bug

### ISSUE THREAD

**Issue by smejkrad** [passbolt/passbolt_browser_extension#63]
## Password generator cycle bug
* Passbolt Version: v2.7.1 - Welcome To The Jungle
* Platform and Target: all
-- Browser: all

### Problem description
In creating user's resources with random password generation there is a cycle comparing expected entropy (function generate() in secretComplexity.js), which is great idea. The problem is that expected entropy will be higher than entropy of generated password every time and the cycle takes the last generated password every time. **I have found the colon char (":") twice in MASKS.special variable.** This cause the generated password entropy was calculated from maximum 94 chars (using MASKS.special.size) and expected entropy from maximum 95 chars (using mask.length on merged array).

**Comment by stripthis** [comment]
Thanks for the bug report, we'll look into it.

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.3
