### ISSUE TITLE
"Remember until I log out" function doesn't apply when you open passbolt

### ISSUE THREAD

**Issue by rgpublic** [passbolt/passbolt_browser_extension#68]
Don't know if it's really a bug but at least it's a major inconvenience: We now have the new browser extension where you can enter your password right in the browser and access your passwords/autofill. Really cool! But: when I click on the "Open passbolt" button for more detailed password management and try to access or add new passwords there I'll have to type my password again. This is quite annoying. It would be cool if your authentication state within the extension could somehow be transferred over to the passbolt website.

**Comment by stripthis** [comment]
@rgpublic thanks for the report we'll look into it. I'm pretty sure @cedricalfonsi already knows about it.

**Comment by cedricalfonsi** [comment]
Fixed with v2.11.0
