### ISSUE TITLE
Login : Cannot read property '1' of null.

### ISSUE THREAD

**Issue by Peter-Mulligan** [passbolt/passbolt_browser_extension#69]
## Cannot read property '1' of null
* v2.9.1
* Chrome plugin and privately hosted web portal (community edition)

### What you did
Tried to log in through plugin and web portal.

### What happened
Received the error "Cannot read property '1' of null".

### What you expected to happen
I expected to log in.

![passbolt](https://user-images.githubusercontent.com/44398776/56719251-467df480-6738-11e9-88e9-f7086c75f86c.png)

**Comment by Peter-Mulligan** [comment]
For context, it was working fine yesterday morning, and it still works fine for ~50% of the people at the company.

**Comment by stripthis** [comment]
@Peter-Mulligan thanks for the report. This issue is present with passbolt API version < 2.2. We're working on a fix that will be published in an hour or so, but we invite you to update your instance as soon as possible.

**Comment by cedricalfonsi** [comment]
Fixed with v2.9.2

**Comment by Peter-Mulligan** [comment]
Thanks for the speedy reply/fix guys. :)
