### ISSUE TITLE
Autofill for self-hosted GitLab instance does not work

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_browser_extension#70]
Technically autofill does work but the wrong form gets populated. The self-hosted GitLab UI shows a login form with 2 tabs, one for LDAP logins, one for Standard logins (GitLab only users). The Standard login tab with the login form is active by default. When using autofill the form for the LDAP login get's populated, not the form that is active (visible) by default.

**Comment by stripthis** [comment]
@shochdoerfer thanks for the report, this is very usefull.

@cedricalfonsi I guess we should check for form fields visibility when they are severals, that should solve this one.

**Comment by shochdoerfer** [comment]
HTML-wise the LDAP form is located "before" the other form. So, I would assume you fill the first "password" form you can find.

**Comment by stripthis** [comment]
@shochdoerfer yes that's correct, that's why looking for visibility in case they are several should do the trick.

**Comment by cedricalfonsi** [comment]
Visibility should solve #71 too

**Comment by stripthis** [comment]
Fixed with v2.10.2
