### ISSUE TITLE
Feature: Show Password

### ISSUE THREAD

**Issue by coinplus-sa** [passbolt/passbolt_browser_extension#72]
Hello, 
I would like to ask for a feature which is the possibility to reveal a password in plain text.
The use case is: when using passbolt to store a password and when using this password on another device (for example a smartphone).
Suggestion: type of password set by the owner to specify if the password can be revealed on not.

Thanks

**Comment by LanceSandino** [comment]
Not sure if you noticed, but if you click on the dots (password) it gets copied to clipboard.
So you could paste it somewhere (like the URL bar) and then input it on your phone -- or if you have  an iphone, it should paste to your iphone :)

**Comment by coinplus-sa** [comment]
Hello Lance,
This method is not possible, here is why:
Passbolt server in VPN.
Desktop connected on the VPN with the extension.
Phone not connected to the VPN, therefore passbolt extension not on the phone, no copy paste possible.

I know it is possible to copy paste in a text editor, and that is what we do, but I think the option to reveal could be useful too.

Benoit

**Comment by stripthis** [comment]
Hi there,

Please use the forum for feature request. We only keep track off bugs in the github issues to avoid clutter.

I moved the discussion here: https://community.passbolt.com/t/as-a-logged-in-user-i-can-click-on-a-button-to-see-a-given-password/2069

**Comment by coinplus-sa** [comment]
merci :)

**Comment by jpstotz** [comment]
Is it normal that the "Show Password" feature uses a font that makes it impossible to distinguish between a small L `l` and a large I `I`?

Take for example the password `lIlIlIlIlIlIlIlIlI`:
![image](https://user-images.githubusercontent.com/924885/232038222-a994cd12-bed7-42c1-b613-44f3fbfef78a.png)
