### ISSUE TITLE
Not working in mobile versions of the browsers

### ISSUE THREAD

**Issue by barolo** [passbolt/passbolt_browser_extension#74]
I wasn't very suprised to see it nor working with chromium based browsers, since addon upport is fresh  ( kiwi being one ) but it doesn't even work in mobile Firefox

**Comment by cedricalfonsi** [comment]
Hello @barolo,

Thank you for your report.

> I wasn't very suprised to see it nor working with chromium based browsers

For now Passbolt provides official support for chrome and firefox only. But we got report from the community who makes the Passbolt extension working with brave by instance, which is also chromium based.

![Screenshot 2019-05-14 at 17 42 45](https://user-images.githubusercontent.com/1582917/57696958-b9132d80-766f-11e9-8e3b-83608e2f9a6b.png)

> but it doesn't even work in mobile Firefox

This is not a bug. The addon has not for aim to work on mobile, however a mobile application is scheduled on the [roadmap](https://www.passbolt.com/roadmap) for this year.
