### ISSUE TITLE
Firefox ESR: copying passwords does not work from the quickaccess

### ISSUE THREAD

**Issue by imrejonk** [passbolt/passbolt_browser_extension#75]
## Firefox 60: copying passwords does not work
* Passbolt Version: 2.10.1
* Platform and Target:
-- Browser: Firefox 60.6.3esr 64-bit (Debian 9 default, clean install)
-- Web server: Official Passbolt Docker container, nginx reverse proxy

### What you did
I store account credentials for website X in Passbolt. I navigate to website X's login page, click the Passbolt icon in Firefox' overflow menu, click the account entry and click on the obfuscated password.

### What happened
A little loading icon next to the obfuscated password starts spinning. I wait 10 seconds, give up and hope that Passbolt has copied the password for me and that the loading icon is just a UI bug. Unfortunately this doesn't work, Passbolt has not copied the password for me.

### What you expected to happen
The Passbolt browser extension should copy the password and the loading icon should quickly be replaced by a checkmark or something to indicate that copying the password has succeeded.

**Comment by cedricalfonsi** [comment]
Hello @imrejonk,

Thank you for your report.

This is a known bug, the quickaccess copy to clipboard feature doesn't work with Firefox < 63 and so Firefox ESR. A new version of the ESR should be proposed to download on 9th July as per their calendar. However the update from the previous ESR will only be proposed on 23th October.

> From a major version to the other (example: the 52 to 60 migration), the updates will be proposed only after the X.2.0 version is released

![release-overview-high-res d3c9788f2dd1](https://user-images.githubusercontent.com/1582917/57931138-6f2b8100-78d5-11e9-97d4-2c968e6ff749.png)
source: https://www.mozilla.org/en-US/firefox/organizations/

Note that the copy to clipboard works well through the web UI of passbolt. Bear with us, we are working hard to make the application better day after day.

**Comment by cedricalfonsi** [comment]
It is now supported by the new Firefox ESR 68

**Comment by imrejonk** [comment]
Hi @cedricalfonsi, thanks for the heads up! It's working perfectly in Firefox ESR 68 :+1:

Let's see how long it takes until ESR 68 is in the Debian stable repositories. Looks like Mozilla is still supporting the old ESR for [at least another 12 weeks](https://www.mozilla.org/en-US/firefox/organizations/).

For those who want to use ESR 68 right now in Debian stable, take a look at [the Debian Wiki page](https://wiki.debian.org/Firefox#Firefox_Stable.2C_Beta_and_Nightly). I performed these steps:

1. [Download](https://www.mozilla.org/en-US/firefox/organizations/all/) Firefox ESR 68
2. Extract the archive to ~/.local/lib
3. Symlink ~/.local/lib/firefox/firefox to ~/.local/bin/firefox-esr
4. Add ~/.local/bin to your PATH by adding this entry to your ~/.profile: `PATH=~/.local/bin:$PATH`
5. Copy /usr/share/applications/firefox-esr.desktop to ~/.local/share/applications/firefox-esr.desktop and edit the `Exec` and `Icon` values. Use full paths!
6. Check your work with `desktop-file-validate ~/.local/share/applications/firefox-esr.desktop`. It should exit without error.

The Firefox ESR menu item and the `firefox-esr` commands should now open ESR 68.
