### ISSUE TITLE
Make extension compatible with Vivaldi again

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_browser_extension#76]
Whilst older versions of the Passbolt extension run fine with Vivaldi, the latest version (2.10.1) gives me an error message stating that "Passbolt is not available for your browser".

**Comment by cedricalfonsi** [comment]
Hello @shochdoerfer,

Sorry to hear that you are experiencing problem !

When the extension is not installed already and you are on the login page, passbolt does not detect the browser as a compatible browser. 

However I installed manually the passbolt extension from the [chrome web store](https://chrome.google.com/webstore/detail/passbolt-extension/didegimhafipceonhjepacocaffmoppf?hl=en) with Vivaldi 2.5.1525.43 on MacOSX and it works fine here.

**Comment by shochdoerfer** [comment]
Hm, wired. It's working again.

I had the extension installed in Vivaldi, visited Passbolt homepage (our self hosted instance) and got the error message. Not sure what happened, the error message is gone and I can use the plugin again.

**Comment by stripthis** [comment]
@shochdoerfer it could be due to an update. e.g. the page was opened when an update took place in the background. I don't think the extension behaves well in this use case, generally restarting the browser helps.
