### ISSUE TITLE
Autofill does not work on portal.office.com and reddit

### ISSUE THREAD

**Issue by ParkHost** [passbolt/passbolt_browser_extension#78]
Really liked the web extension so far, this feature made Passbolt my primary password-database!

Am missing the following feature:
Let me choose the credential fields of a website, same as httpkeepass extension.

The following bugs are noticed:
The webextension has problems with sites only asking the username/email or password.
Like portal.office.com and the PI-Hole admin login.

Also the login at the reddit website is having some issues with logging in.

**Comment by stripthis** [comment]
Thanks for the report. What's the url for the PI-Hole admin login? That would be helpful to investigate, thanks. 

I moved your suggestion there: https://community.passbolt.com/t/as-a-user-i-can-define-css-selectors-to-help-the-extension-fill-in-forms/1842

**Comment by MrHpower** [comment]
it is only available from the LAN side, i further tested it out and it doesn't working when i access it over the IP address, when accessing it over the DNS name "http://pi.hole/admin" it is works just fine.

**Comment by FlyingWraptor** [comment]
@stripthis  You can find the pi-hole login template in the repository in github: https://github.com/pi-hole/AdminLTE/blob/af8c926cefd3f06dbbba0131b7644a1bb45cd514/scripts/pi-hole/php/loginpage.php
If that's what you require

**Comment by cedricalfonsi** [comment]
Fixed with v2.11.0
