### ISSUE TITLE
Remember password time amount dropdown doesn't display properly

### ISSUE THREAD

**Issue by dgalezow** [passbolt/passbolt_browser_extension#80]
## Remember password time amount dropdown doesn't display properly
* Passbolt Version: don't know
* Platform and Target:
-- Browser: Chrome  74.0.3729.169 (64-bit)

### What you did
Open passbolt in new tab
Try to copy password
Select amount of time to remember password

### What happened
Dropdown with options how long password should be remembered is unreadable
![image](https://user-images.githubusercontent.com/48494061/59597029-25fb6680-90f9-11e9-8a3c-7d1f20d1f580.png)

Issue doesn't occur every time. Clearing cache does not help

### What you expected to happen
Dropdown options should display properly

**Comment by PriyangaV** [comment]
Hello @dgalezow Sorry to hear that you are experiencing problem! 
We couldn't reproduce the issue you have reported on our end. In order to help you we would need a little more details which will put us in a better position to analyse and debug this issue.

Passbolt Version:
OS Version:
API response of this url https://{passbolt_domain}/settings.json:

And also we could see that you are using an older version of Chrome, do please let us know if you're still encountering the issue after updating Chrome.

**Comment by dgalezow** [comment]
I have updated my chrome yesterday, and today have same issue. 

Also noticed, that it occurs always after refreshing Passbolt tab in browser, but when i change it to other tab, and then got back to it, it fixes itself.

Passbolt Version: I have no idea how to check it, is like in API response 2.9.0 ?
OS Version: Windows 10 Pro 64 bit version 1903 
API response: `{"header":{"id":"ebdaf81f-1af4-43d7-9c80-9addf3f535ff","status":"success","servertime":1565069601,"title":"app_settings_index_success","action":"bef9f3ca-86ef-5c6a-9b38-320e03ceb5df","message":"The operation was successful.","url":"\/settings.json","code":200},"body":{"app":{"version":{"number":"2.9.0","name":"Paint It Black"},"url":"https:\/\/passbolt.divante.pl\/","debug":0,"server_timezone":"UTC","session_timeout":"1440","image_storage":{"public_path":"img\/public\/"}},"passbolt":{"edition":"ce","plugins":{"import":{"version":"2.0.1","config":{"format":["kdbx","csv"]}},"export":{"version":"2.0.0"},"rememberMe":{"version":"2.0.0","options":{"300":"5 minutes","900":"15 minutes","1800":"30 minutes","3600":"1 hour","-1":"until I log out"}},"log":{"version":"1.0.0"}}}}}`

**Comment by stripthis** [comment]
Closing as this is stale. Feel free to reopen if you have a procedure to reproduce the issue.
