### ISSUE TITLE
Can't login on chrome beta 79

### ISSUE THREAD

**Issue by theblackhole** [passbolt/passbolt_browser_extension#85]
## Can't login on chrome beta 79
* Passbolt Version: 2.11.0
* Passbolt Extension Version: 2.11.1
* Platform and Target:
-- Browser: Chrome 79.0.3945.16 beta (64 bits)
-- Web server: Docker

### What you did
I tried to login on my passbolt server.

### What happened
Web page: The login refreshed and the passphrase form has been cleared (or there's a redirection on the login page after login), with no error message.
Extension window: Stuck at "Retrieving your passwords"

### What you expected to happen
A redirection to my list of passwords after successful login

I can reproduce the bug on a Windows and Linux pc with the same chrome version. It works perfectly fine on firefox.
I reinstalled the extension and restarted the server (docker-compose down then up) I still have the same issue.

**Comment by stripthis** [comment]
Hello,

I just tested passbolt v2.11 on Chrome Version 79.0.3945.16 (Official Build) beta (64-bit) and could login. I tried playing with the settings such as disabling third party cookies but i'm not able to reproduce. I suspect this has to do with your cookies settings (or existing cookies not being cleared properly).

Can you open chrome://extensions/ and click on passbolt extension and click on inspect view: index.html. Clear the content of the window, try to login again and see if there is any error there.

**Comment by theblackhole** [comment]
I got some 403 from the server. It's weird because it works on firefox and also doesn't work on chrome 79 on another pc. (Of course I use the same account with the same private key on all machines)

Inspect view console output:
![image](https://user-images.githubusercontent.com/7818904/68300472-22637e80-009e-11ea-83b6-a54e5480ec85.png)

Inspect view network output:
![image](https://user-images.githubusercontent.com/7818904/68300551-4a52e200-009e-11ea-9aee-036c3049de1d.png)

Content of `/account/settings.json?api-version=v2` response :
```json
{
  "header": {
    "id": "56641158-160f-4231-a2ff-a4336d173d7b",
    "status": "error",
    "servertime": 1573037472,
    "title": "app_errors_notSupported_error",
    "action": "90fcfe14-8e9e-57b2-bdcb-06b7a73452c5",
    "message": "You need to login to access this location.",
    "url": "\/account\/settings.json?api-version=v2",
    "code": 403
  },
  "body": ""
}
```

Content of `/settings.json?api-version=v2` response :
```json
{
  "header": {
    "id": "edefe75b-b190-49f1-9d64-74c4a6fa699e",
    "status": "success",
    "servertime": 1573037473,
    "title": "app_settings_index_success",
    "action": "bef9f3ca-86ef-5c6a-9b38-320e03ceb5df",
    "message": "The operation was successful.",
    "url": "\/settings.json?api-version=v2",
    "code": 200
  },
  "body": {
    "app": {
      "url": "https:\/\/mypassboltserver\/"
    },
    "passbolt": {
      "edition": "ce",
      "plugins": {
        "rememberMe": {
          "options": {
            "300": "5 minutes",
            "900": "15 minutes",
            "1800": "30 minutes",
            "3600": "1 hour",
            "-1": "until I log out"
          }
        }
      }
    }
  }
}
```

Content of `/auth/is-authenticated.json`:
```json
{
  "header": {
    "id": "650c20d6-a84a-4b43-a0f1-f917fd9f5f7f",
    "status": "error",
    "servertime": 1573037551,
    "title": "app_auth_isAuthenticated_error",
    "action": "4d2d5c43-a76a-5d4a-8f47-2b1f0268e3d6",
    "message": "You need to login to access this location.",
    "url": "\/auth\/is-authenticated.json",
    "code": 403
  },
  "body": ""
}
```

**Comment by theblackhole** [comment]
Passbolt works again in Chrome with the new 79.0.3945.29 beta update. So it seems like it was indeed a Chrome issue.
