### ISSUE TITLE
Firefox: Browser Extension does not finish setup/login

### ISSUE THREAD

**Issue by mbiberhofer** [passbolt/passbolt_browser_extension#86]
## Firefox: Browser Extension does not finish setup/login
* Passbolt Version: via DockerHub -- `passbolt/passbolt@sha256:dd72c6da8d12e4c30a651dcb415ae56e643bcff5e985aa4a6dcfacccb601fce0 # 2.11.0-debian`

* Platform and Target:
-- Browser: Firefox 70.0.1
-- Web server: The one from the image, running behind haproxy (image `haproxy@sha256:4c6028a51944d285461417e2fc08e2f26f14998205ff2747e9ebab151d243b77 # haproxy:1.8.20-alpine`
-- etc.: System runs behind a proxy that authenticates client connections via TLS client certificates

### What you did

- Installed & basically configured passbolt on Docker
- Installed most recent passbolt Firefox extension: 2.11.1
- Created an admin account according to https://hub.docker.com/r/passbolt/passbolt: `docker exec passbolt su -m -c "/var/www/passbolt/bin/cake passbolt register_user -u <mail> -f <firstname> -l <surname> -r admin" -s /bin/sh www-data`
- Pasted URL created by the command into firefox
- Followed setup instructions until step 5, "Login !"

### What happened
- At step 5, "Login", a Success-Message is being shown.
- "Spin Wheel" is being shown infinitely.
- "Click here if you can't wait" has no action/anchor defined.
- Console shows two messages. See attached Screenshot

![2019-11-12-063931_2556x1121_scrot](https://user-images.githubusercontent.com/10251814/68652845-456cb300-0522-11ea-9133-9ad97cc9164c.png)

### What you expected to happen
- Finishing the setup to start using passbolt

FYI: I don't have Chrome installed. I'll post feedback on Chrome if a colleague of mine has some time to spare.

Feel free to ask for more information, I'll try to be responsive. :-)

**Comment by cedricalfonsi** [comment]
Hello @mbiberhofer,

Thank you for the report.

I'm able to reproduce the bug by using a security token with a length inferior to 3 characters.

Are you in the same situation ? If yes then the workaround is to use a security token of 3 characters. I'm marking the ticket as a bug and will take care of it.

Best regards.

**Comment by mbiberhofer** [comment]
I can confirm that this happens only when the security token is < 3 characters in length. I've switched to a 3-chracter security token, now the setup process is finished successfully.

Thank you very much for your fast response and provided hotfix! :-)

**Comment by stripthis** [comment]
This is fixed with 2.13. (the chrome extension is still in google purgatory though).
