### ISSUE TITLE
Firefox/Chrome: batchSize of 100 is too big when exporting more than 90 passwords

### ISSUE THREAD

**Issue by s4ke** [passbolt/passbolt_browser_extension#87]
see original issue in passbolt_api https://github.com/passbolt/passbolt_api/issues/330

**Comment by s4ke** [comment]
Validated released version with updated version 2.12 in Firefox.

**Comment by cedricalfonsi** [comment]
Thank you for the contribution @s4ke, it is very much appreciated.
Note that the chrome version is not yet published, it should be in the coming days.
