### ISSUE TITLE
Account recovery fails if logged in, but gives a bad/wrong error message.

### ISSUE THREAD

**Issue by jtillman-OMB** [passbolt/passbolt_browser_extension#93]
This is the crux of my issue from the community forums here: https://community.passbolt.com/t/account-recovery-fails-this-key-doesnt-match-any-account/2503/6?u=jtillman

Issue being, if you're logged into the passbolt app while performing the /recovery workflow (in my case, my profile page was still open in a different browser tab) you are given an error message which says 'This key doesn\'t match any account.', which doesn't reflect the actual problem, which is that the user has to be logged out to perform account recovery.

It'd be great if you *could* perform recovery (insofar as you're changing your keyring passphrase) while still logged in, but just having a better/more meaningful error message would have been very helpful.

The error message is located here: https://github.com/passbolt/passbolt_browser_extension/blob/8029423738dba52db0348c2d423e8b7e7d09460c/src/all/data/js/setup/step/importKey.js#L196

**Comment by jtillman-OMB** [comment]
You also get this same error message if you're performing an account recovery but the server (running passbolt_api) has path or permission issues with the location of its gpg keys.

This error message in general should be revisited and more useful error codes should be generated at this point.

**Comment by stripthis** [comment]
Fixed in 2.3.17
